// The pure half of the macOS update flow, kept out of updater.ts so it can be
// tested without Electron: a wrong answer from either function bricks or loops
// auto-update, and neither needs a running app to exercise.

export interface MacFeed {
  version: string
  assets: Array<{ name: string; sha512: string }>
}

// latest-mac.yml is generated by electron-builder with a fixed shape — this is
// a targeted extraction, not a yaml parser. Split per `- url:` entry and find
// sha512 anywhere in the entry, so extra fields (size, blockMapSize, a future
// addition) or field reordering can't silently produce zero assets.
export function parseFeed(text: string): MacFeed {
  const version = /^version:\s*(\S+)/m.exec(text)?.[1]
  if (version === undefined) throw new Error('update feed: no version field')
  const assets: MacFeed['assets'] = []
  for (const entry of text.split(/-\s+url:/).slice(1)) {
    const name = /^\s*(\S+)/.exec(entry)?.[1]
    const sha512 = /\bsha512:\s*(\S+)/.exec(entry)?.[1]
    if (name !== undefined && sha512 !== undefined) assets.push({ name, sha512 })
  }
  if (assets.length === 0) throw new Error('update feed: no assets parsed')
  return { version, assets }
}

export function isNewer(remote: string, local: string): boolean {
  const norm = (v: string): number[] =>
    v.replace(/^v/, '').split('-')[0].split('.').map((n) => Number(n) || 0)
  const a = norm(remote)
  const b = norm(local)
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    const d = (a[i] ?? 0) - (b[i] ?? 0)
    if (d !== 0) return d > 0
  }
  return false
}

// Which binary a relaunch should spawn after the macOS swap. The swap keeps the
// bundle's old *directory* name but fills it with the new version's contents,
// and a bundle's executable is named after productName — which changed in 0.2.2
// ("Bevy Scene Editor" → "Decentraland Studio"). So for anyone updating from
// 0.2.1 or earlier the path we booted from no longer exists, app.relaunch()
// spawns nothing, and the app simply never comes back. null = the default (our
// own execPath) is still right.
export function pickRelaunchExec(bootedExec: string, bundleBinaries: string[]): string | null {
  const name = bootedExec.split('/').pop() ?? bootedExec
  if (bundleBinaries.includes(name)) return null
  // an Electron bundle carries exactly one binary in Contents/MacOS; if that
  // ever stops holding, guessing is worse than letting the default fail loudly
  return bundleBinaries.length === 1 ? bundleBinaries[0] : null
}
