// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
import {
  InputAction,
  PlayerIdentityData,
  Schemas,
  engine,
  pointerEventsSystem,
  type Entity
} from '@dcl/sdk/ecs'
import { isServer, registerMessages, syncEntity } from '@dcl/sdk/network'
import { Storage } from '@dcl/sdk/server'
import { createRpc, type Rpc } from './rpc'
import { markServerReady, serverLifeState, startServerLife } from './serverLife'
import { protectSynced } from './protectedSync'
import { serverState, type ServerState } from './serverState'
import { FlushDebouncer } from './playerStore'
import { getServerTime, initTimeSync } from './timeSync'
import { GameCore, type CorePorts, type Player } from './pure/gameCore'

// The creator's one object. Every scene runs one shared copy — the game — plus
// a copy per player's screen; `game` is how a script talks to the shared one.
// This file is transport and timing only; every rule (direction, one handler
// per name, FIFO, rate limits, the green guard, boot order) lives in
// pure/gameCore.ts, where the harness can reach it.
//
//   game.onMessage('openChest', (data, player) => { ... })   // in the game, for everyone
//   onClick(this.entity, () => void game.send('openChest', { chest: this.entity }))
//
// Timing, solved here once. Schemas must register at module scope (the engine
// seals after load), so ONE rpc namespace carries every ask and ONE broadcast
// envelope carries every tell — creator names are payload, never schema, which
// is why onMessage is legal anywhere: module scope, start(), mid-round. And
// isServer() answers false for every module body, so which transport half
// installs is decided on the first engine tick (the outcomes idiom).
//
// Cross-copy: every prefab carries its own copy of this file, so the whole
// driver — core, rpc, tell room, fact entities — lives on
// globalThis.__dclGame_v1 and is probed by shape. Only the first copy registers
// the schemas; sibling copies adopt its transport objects, which is what keeps
// registration exactly-once.

const GAME_KEY = '__dclGame_v1'
const TELL = 'game.tell'
const PARTICIPANT = 'game'
// Storage namespaces — creators' durable data lives under these forever.
const SAVED_STORE_KEY = 'game.saved'
const PLAYER_STORE_KEY = 'game'

export type { Player }

// Each top-level game.state key rides its own synced entity, so a single write
// stays far from the transport's 12 KB chunk edge and unrelated keys move
// independently. A sibling copy may have defined the component first.
function defineSharedFact() {
  return engine.defineComponent('runtime::SharedFact', {
    key: Schemas.String,
    json: Schemas.String,
    rev: Schemas.Int
  })
}
const SharedFact =
  (engine.getComponentOrNull('runtime::SharedFact') as ReturnType<typeof defineSharedFact> | null) ?? defineSharedFact()

function registerTell() {
  return registerMessages({
    [TELL]: Schemas.Map({ name: Schemas.String, body: Schemas.String, to: Schemas.String })
  })
}
type TellRoom = ReturnType<typeof registerTell>

interface HeldAsk {
  name: string
  json: string
  resolve: (json: string) => void
  reject: (error: Error) => void
}

interface GameDriver {
  core: GameCore
  rpc: Rpc
  tell: TellRoom
  role: 'server' | 'client' | null
  ticking: boolean
  /** every name a handler registered under, so a late server fork can arm them all */
  names: Set<string>
  /** blue asks held while the ladder says waking */
  held: HeldAsk[]
  /** server: fact key → its synced entity */
  factEntities: Map<string, Entity>
  /** server: stale snapshot entities awaiting next-tick removal */
  retirals: Entity[]
  /** client: last rev seen per key, to notice a retired fact's entity vanish */
  seenRevs: Map<string, number>
  saved: ServerState<Record<string, unknown>> | null
  dirtyPlayers: Map<Player, Record<string, unknown>>
  flush: FlushDebouncer
}

// Byte-identical copies of this file are still separate module instances, so
// the shared driver is probed by shape — instanceof would reject a sibling's.
function isDriver(value: unknown): value is GameDriver {
  return (
    typeof value === 'object' &&
    value !== null &&
    'core' in value &&
    typeof value.core === 'object' &&
    value.core !== null &&
    'handleAsk' in value.core &&
    typeof (value.core as { handleAsk: unknown }).handleAsk === 'function' &&
    'names' in value &&
    value.names instanceof Set &&
    'held' in value &&
    Array.isArray(value.held)
  )
}

function driver(): GameDriver {
  const globals = globalThis as unknown as Record<string, unknown>
  const current = globals[GAME_KEY]
  if (isDriver(current)) return current
  const created = createDriver()
  globals[GAME_KEY] = created
  return created
}

function createDriver(): GameDriver {
  const d: GameDriver = {
    core: new GameCore(makePorts(() => d)),
    rpc: createRpc('game'),
    tell: registerTell(),
    role: null,
    ticking: false,
    names: new Set<string>(),
    held: [],
    factEntities: new Map<string, Entity>(),
    retirals: [],
    seenRevs: new Map<string, number>(),
    saved: null,
    dirtyPlayers: new Map<Player, Record<string, unknown>>(),
    flush: new FlushDebouncer()
  }
  return d
}

function makePorts(self: () => GameDriver): CorePorts {
  return {
    now: () => Date.now(),
    sendAsk: (name, json) => {
      const d = self()
      // rpc's retry budget (~12 s) is shorter than a production cold start
      // (~15 s): while the ladder says waking, hold the ask — the client tick
      // drains the queue once the first heartbeat lands, so a cold start is a
      // spinner, never a mystery timeout.
      if (serverLifeState() === 'waking') {
        return new Promise<string>((resolve, reject) => {
          d.held.push({ name, json, resolve, reject })
        })
      }
      return d.rpc.call<string>(name, json)
    },
    sendTell: (name, json, to) => {
      try {
        self().tell.send(TELL, { name, body: json, to: to ?? '' })
      } catch {
        // transport down — a tell is a moment, it fades
      }
    },
    publishFact: (key, json, rev) => {
      const d = self()
      const existing = d.factEntities.get(key)
      if (existing !== undefined) {
        const fact = SharedFact.getMutable(existing)
        fact.json = json
        fact.rev = rev
        return
      }
      const entity = engine.addEntity()
      SharedFact.create(entity, { key, json, rev })
      // auto sync id + refuse-all validator, fused: never synced-but-unguarded
      syncEntity(entity, [SharedFact.componentId])
      protectSynced(entity, [SharedFact], () => false)
      d.factEntities.set(key, entity)
    },
    retireFact: (key) => {
      const d = self()
      const entity = d.factEntities.get(key)
      if (entity === undefined) return
      d.factEntities.delete(key)
      // removeEntity waits a tick — never in the frame that republishes (the
      // NetworkEntity survives until the CRDT flush)
      d.retirals.push(entity)
    },
    emitError: (card) => {
      console.error(`[${card.side}] ${card.name}: ${card.message}`)
    },
    devWarn: (message) => {
      console.log(`[game] ${message}`)
    },
    loadSaved: async () => {
      const store = savedStore(self())
      await store.restore()
      return { ...store.get() }
    },
    storeSaved: (key, value) => {
      const d = self()
      savedStore(d).patch({ [key]: value })
      d.flush.mark(Date.now())
    },
    loadPlayerData: async (player) => {
      const raw = await Storage.player.get<unknown>(player, PLAYER_STORE_KEY)
      return typeof raw === 'object' && raw !== null ? { ...(raw as Record<string, unknown>) } : {}
    },
    storePlayerData: (player, data) => {
      const d = self()
      d.dirtyPlayers.set(player, data)
      d.flush.mark(Date.now())
    }
  }
}

function savedStore(d: GameDriver): ServerState<Record<string, unknown>> {
  if (d.saved === null) {
    d.saved = serverState<Record<string, unknown>>({ key: SAVED_STORE_KEY, defaults: () => ({}), persist: true })
  }
  return d.saved
}

// Write-behind checkpoint: saved and playerData land after the debounce window,
// never per tick — storage writes are capped. A failed write stays dirty and
// re-arms the window.
async function flushDurable(d: GameDriver): Promise<void> {
  if (d.saved !== null) await d.saved.flush()
  for (const [player, data] of [...d.dirtyPlayers]) {
    const ok = await Storage.player.set(player, PLAYER_STORE_KEY, data)
    if (!ok) {
      d.flush.mark(Date.now())
      continue
    }
    if (d.dirtyPlayers.get(player) === data) d.dirtyPlayers.delete(player)
  }
}

// Every ask rides the one rpc namespace; the method map is per-name, so a
// handler can arm at any time. The player's durable record is restored before
// their first green handler, so playerData(p).get() never races the load.
function armAsk(d: GameDriver, name: string): void {
  d.rpc.handle(name, (body, from) => {
    const player = from.toLowerCase()
    const json = typeof body === 'string' ? body : JSON.stringify(body ?? null)
    return d.core.restorePlayerData(player).then(() => d.core.handleAsk(name, json, player))
  })
}

function myAddress(): string {
  return PlayerIdentityData.getOrNull(engine.PlayerEntity)?.address.toLowerCase() ?? ''
}

function armTick(d: GameDriver): void {
  if (d.ticking) return
  d.ticking = true
  engine.addSystem(
    () => {
      const live = driver()
      if (live.role === null) {
        // the platform has resolved the role by the first tick — fork now, and
        // skip the role tick this frame so boot's retirals wait a full tick
        fork(live)
        return
      }
      if (live.role === 'server') serverTick(live)
      else clientTick(live)
    },
    undefined,
    'runtime-game'
  )
}

function fork(d: GameDriver): void {
  const server = isServer()
  d.role = server ? 'server' : 'client'
  d.core.setRole(server)
  initTimeSync()
  startServerLife(PARTICIPANT)
  if (server) {
    for (const name of d.names) armAsk(d, name)
    // the CRDT snapshot outlives the isolate: adopt what survived, then boot
    // retires it (state resets when the game sleeps) and republishes fresh
    const adopted: Array<{ key: string; json: string; rev: number }> = []
    for (const [entity] of engine.getEntitiesWith(SharedFact)) {
      const fact = SharedFact.get(entity)
      adopted.push({ key: fact.key, json: fact.json, rev: Number(fact.rev) })
      d.factEntities.set(fact.key, entity)
    }
    void d.core.bootServer(adopted).then(() => markServerReady(PARTICIPANT))
  } else {
    d.tell.onMessage(TELL, (msg) => {
      if (msg.to !== '' && msg.to !== myAddress()) return
      d.core.handleTell(msg.name, msg.body)
    })
  }
}

function serverTick(d: GameDriver): void {
  for (const entity of d.retirals.splice(0)) engine.removeEntity(entity)
  d.core.flushState()
  if (d.flush.isDue(Date.now())) {
    d.flush.clear()
    void flushDurable(d)
  }
}

function clientTick(d: GameDriver): void {
  const present = new Set<string>()
  for (const [entity] of engine.getEntitiesWith(SharedFact)) {
    const fact = SharedFact.get(entity)
    const rev = Number(fact.rev)
    present.add(fact.key)
    d.core.applyFact(fact.key, fact.json, rev)
    d.seenRevs.set(fact.key, rev)
  }
  for (const [key, rev] of [...d.seenRevs]) {
    if (present.has(key)) continue
    // the game retired the fact's entity (boot wipe) — the mirror follows
    d.seenRevs.delete(key)
    d.core.applyRetire(key, rev + 1)
  }
  if (d.held.length > 0 && serverLifeState() !== 'waking') {
    for (const ask of d.held.splice(0)) {
      d.rpc.call<string>(ask.name, ask.json).then(ask.resolve, ask.reject)
    }
  }
}

// One handler per name: a re-registration from the same script must replace (a
// prefab placed twice shares one handler) while a second script claiming the
// name must error. The call site is the only script identity that exists at
// runtime — best effort: a bundle that flattens filenames degrades to replace
// semantics, and the static check owns the edit-time error.
function callerScript(): string {
  for (const line of (new Error().stack ?? '').split('\n').slice(1)) {
    const match = /([^/\\ ('")]+\.[tj]sx?)/.exec(line)
    if (match !== null && match[1] !== 'game.ts' && match[1] !== 'gameCore.ts') return match[1]
  }
  return 'scene'
}

export const game = {
  /** Runs once when the game wakes up (not per player, not per round). */
  onStart(fn: () => void | Promise<void>): void {
    driver().core.onStart(fn)
  },
  /** Facts every player agrees on; a player who joins late sees them automatically. */
  get state(): Record<string, unknown> {
    return driver().core.state
  },
  /** Changes shared facts — only code inside game.onMessage (or game.onStart) can call it. */
  setState(patch: Record<string, unknown>): void {
    driver().core.setState(patch)
  },
  /** Every screen, including players who join late. */
  onStateChange(listener: (changed: Record<string, unknown>) => void): void {
    driver().core.onStateChange(listener)
  },
  /**
   * A screen's send asks the game and resolves with the handler's return.
   * The game's send is a moment: shown once, then gone. Players who join later
   * never see it — lasting facts go in game.state. `{to}` reaches one player
   * (weaker delivery — fine for a whisper).
   */
  send(name: string, data?: unknown, opts?: { to?: Player }): Promise<unknown> {
    return driver().core.send(name, data, opts)
  },
  /** In the game it hears players' asks; on a screen it hears the game. */
  onMessage(name: string, fn: (data: unknown, player: Player) => unknown | Promise<unknown>): void {
    const d = driver()
    d.names.add(name)
    d.core.onMessage(name, fn, callerScript())
    if (d.role === 'server') armAsk(d, name)
  },
  /** The shared clock — the same number in the game and on every screen. */
  now(): number {
    return Number(getServerTime())
  },
  /** Survives restarts and re-publishes, unlike game.state. Only the game reads or writes it. */
  saved: {
    get(key: string): unknown {
      return driver().core.saved.get(key)
    },
    set(key: string, value: unknown): void {
      driver().core.saved.set(key, value)
    }
  },
  /** One durable record per wallet, forever. set patches top-level keys. */
  playerData(player: Player): { get(): Record<string, unknown>; set(patch: Record<string, unknown>): void } {
    return driver().core.playerData(player)
  }
}

/**
 * What THIS player clicks, on their screen. Decisions that count for everyone
 * go inside game.onMessage.
 */
export function onClick(entity: Entity, fn: () => void): void {
  pointerEventsSystem.onPointerDown({ entity, opts: { button: InputAction.IA_POINTER } }, fn)
}

armTick(driver())
