// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
import { Transform, engine, type Entity } from '@dcl/sdk/ecs'
import { isServer } from '@dcl/sdk/network'
import { outcomes, type OutcomeEntry, type OutcomeLedger } from './outcomes'
import { createRpc } from './rpc'
import { markServerReady, serverLifeState, startServerLife } from './serverLife'
import { serverState, type ServerState } from './serverState'
import { snapshotRootComponent, spawnedFrom, type Pool } from './spawner'
import { stableId } from './pure/poolState'
import { effectiveScatter, scatterOffset } from './pure/spawnScatter'
import { zoneKey } from './pure/zoneRegistry'
import { composeWorld, identityTransform, type LocalTransform, type WorldTransform } from './pure/worldTransform'
import {
  DESPAWN_KIND,
  SPAWN_KIND,
  alivePairs,
  aliveCount,
  aliveIn,
  applyEntry,
  emptyFold,
  hasSeen,
  isAlive,
  spotOfInstance,
  type SpawnFold
} from './pure/spawnFold'

// Spawn points: copies of a prefab that appear WHILE THE GAME RUNS, and that every
// player sees in the same place at the same time.
//
//   const spot = spawnSpot('Crate Spawner', {
//     pool: pool(prefabRef, 'seeded'),   // opened by the CALLER, never in here
//     spot: this.entity,                 // the point copies appear at
//     atMostAtOnce: 3, lifetimeS: 0, scatterRadius: 2
//   })
//   spot?.request()                      // a press, a zone entry, a script asking
//   requestSpawn('Crate Spawner')        // the same thing, by name, from anywhere
//   retireSpawned(entity)                // this copy is done with
//
// WHAT CROSSES THE WIRE is one number per copy: its instance id, in an outcome
// ledger entry whose value names the spawn point. No position, ever. Each peer
// resolves the spawn point's own world transform locally and offsets the copy by
// scatterOffset(instanceId, radius), which is a pure function of a number both
// sides already agree on — so five copies stand in five places without five
// positions being replicated.
//
// THE MINT IS TWO HOPS, not a direct report. A client asks over rpc
// (`spawnBus.rpc.req`), the server mints the id from PERSISTED state and reports
// it to its own ledger, which validates, appends and broadcasts. Client-minted
// ids repeat after a page reload, and the ledger's own path cannot mint: serve()
// takes instanceId from the payload and puts the validator's value in `value`.
// Each ask carries a nonce minted once per request() and stable across the rpc
// layer's retries, and the server answers a repeat with the id it already minted
// — a retried request can never append twice.
//
// DELIVERY IS UNCONDITIONAL; ONLY MATERIALISATION IS GATED. Every entry is folded
// the moment it arrives, including the catch-up walk's replay — the walk flips
// isSynced() only after its last page, so holding entries back until then would
// drop exactly the history being waited for. Copies are created only once the
// walk has landed, and never on the server: serve() delivers there too, and a
// server that materialised would hold entities nobody asked it to hold.
//
// WHAT SURVIVES A RESTART. The server persists {nextInstanceId, the alive set and
// its lifetime deadlines, the answered nonces, each ledger's last sequence number}
// under serverState('spawnBus'). At boot it rehydrates, hands the ledger a
// synthetic history so sequence numbers CONTINUE rather than restart — a client
// whose stream is at seq 400 drops everything a restarted server numbers 1..400,
// and goes deaf for good — and only then answers markServerReady('spawnBus').
// The bus holds its OWN id on the readiness ladder, next to the carrying prefab's:
// the first heartbeat waits for the last participant, so a prefab that is ready
// the moment its start() returns cannot announce a server whose spawn history has
// not been read back yet.
//
// THE CEILING, stated: a client replays at most 384 ledger entries, so on a
// long-lived server the older pairs are gone and the alive set is reconstructed
// from the server's persisted fold instead of from the log. The press itself is
// client-reported — the server checks the cap, the rate and the id, not whether
// the player was really touching the button. Copies appear AT the spawn point;
// there is no way to spawn at a position computed at runtime.
//
// Cross-copy: every prefab carries its own copy of this file, so the registry and
// the server side live on globalThis.__dclSpawnBus_v1, probed by shape.

const BUS_KEY = '__dclSpawnBus_v1'
const RPC_NAMESPACE = 'spawnBus'
const STATE_KEY = 'spawnBus'
/** The bus's own seat on the readiness ladder, separate from any prefab's. */
const PARTICIPANT = 'spawnBus'
const TRANSFORM = 'core::Transform'
/** Marks a server boot in the ledger, so a surviving client sees the jump and re-walks. */
const RESTART_KIND = 'spawnRestart'
const SWEEP_S = 0.5
const MAX_NONCES = 256
const MIN_REQUEST_INTERVAL_MS = 250
/**
 * How far a restarted server's sequence jumps past the last number it persisted.
 * A flush that did not land before the crash left a few appends unrecorded, and a
 * sequence that moves BACKWARDS is the one failure clients cannot repair.
 */
const SEQ_RESTART_GAP = 512
const PARENT_DEPTH_MAX = 32
const FLUSH_MIN_MS = 1_000

// createRpc registers message schemas, so it runs at module scope — before the
// engine seals — and picks no side: which half installs is decided by the first
// handle()/call(), which only ever runs from a script's start().
const spawnRpc = createRpc(RPC_NAMESPACE)

/** A random per-session salt, so a page reload cannot reuse the nonces it already spent. */
const SESSION = Math.floor(Math.random() * 0xffffffff).toString(36)
let requestCounter = 0

export interface SpawnSpotOptions {
  /** Opened by the CALLER, so the editor's guarantee scan can attribute it to the prefab. */
  pool: Pool
  /** The spawn point. Its WORLD transform is the position; never on the wire. */
  spot: Entity
  atMostAtOnce: number
  /** Seconds a copy sticks around; 0 keeps it until something retires it. Enforced server-side. */
  lifetimeS: number
  scatterRadius?: number
}

export interface SpawnSpot {
  request(): void
  /** The copies THIS client is showing. Always empty on the server, which materialises nothing. */
  alive(): Entity[]
  /** Server reachable AND the ledger caught up — the gate request() reports on. */
  ready(): boolean
}

interface SpotEntry {
  /** the creator's spelling, for logs */
  name: string
  spotId: number
  pool: Pool
  spot: Entity
  atMostAtOnce: number
  lifetimeMs: number
  scatterRadius: number
  ledgerKey: string
  live: Map<number, Entity>
  notReadyLogged: boolean
}

interface LedgerBinding {
  key: string
  ledger: OutcomeLedger
  fold: SpawnFold
  lastSeq: number
  armed: boolean
}

interface SavedInstance {
  id: number
  spot: number
  key: string
  /** absolute ms this copy disappears at; 0 keeps it */
  until: number
}

interface SavedSpawns {
  nextInstanceId: number
  alive: SavedInstance[]
  nonces: Array<{ nonce: string; id: number }>
  lastSeqByKey: Array<{ key: string; seq: number }>
}

interface ServerSide {
  store: ServerState<SavedSpawns>
  restored: boolean
  /** set when persisted state was unreadable: late-binding ledgers must jump too */
  blindBase: number
  dirty: boolean
  lastFlushMs: number
  nextInstanceId: number
  /** instance id → the absolute ms it disappears at */
  expiries: Map<number, number>
  /** `${wallet}:${nonce}` → the id already minted for it, insertion-ordered and bounded. */
  nonces: Map<string, number>
  askedAtMs: Map<string, number>
  rejections: Set<string>
}

interface SpawnHub {
  spots: Map<number, SpotEntry>
  ledgers: Map<string, LedgerBinding>
  installed: boolean
  lifeStarted: boolean
  server: ServerSide | null
}

/**
 * Register a spawn point. Returns null — logged, never thrown — when the point
 * cannot work: a blank name, a point sitting inside a pooled copy (its clone
 * would register a second time under the same name), or a pool that is not open.
 */
export function spawnSpot(name: string, opts: SpawnSpotOptions): SpawnSpot | null {
  const display = name.trim()
  if (display === '') {
    console.log(
      '[spawnBus] a spawn point needs a name — give this entity a Name in the hierarchy, or copies made by two spawn points would share one identity'
    )
    return null
  }
  const walk = chainOf(opts.spot)
  if (walk.pooled) {
    console.log(
      `[spawnBus] '${display}' sits inside a copy this scene spawns, so it does nothing — a spawn point must be placed in the scene, never inside a prefab that gets spawned`
    )
    return null
  }
  const shared = bus()
  const spotId = stableId(zoneKey(display))
  const existing = shared.spots.get(spotId)
  if (existing !== undefined && existing.spot !== opts.spot) {
    console.log(
      `[spawnBus] two spawn points are both named '${display}' — rename one, the copies of the second are not being made`
    )
    return null
  }
  const cap = clampToPool(display, opts.atMostAtOnce, opts.pool)
  const entry: SpotEntry = {
    name: display,
    spotId,
    pool: opts.pool,
    spot: opts.spot,
    atMostAtOnce: cap,
    lifetimeMs: Math.max(0, numberOf(opts.lifetimeS, 0)) * 1000,
    scatterRadius: Math.max(0, numberOf(opts.scatterRadius, 0)),
    ledgerKey: opts.pool.prefab,
    live: existing?.live ?? new Map<number, Entity>(),
    notReadyLogged: false
  }
  join(shared)
  const binding = bindLedger(shared, entry.ledgerKey)
  armValidators(shared, binding)
  shared.spots.set(spotId, entry)
  install(shared)
  return {
    request: () => request(shared, entry),
    alive: () => [...entry.live.values()],
    ready: () => ready(shared, entry)
  }
}

/** Ask a spawn point for a copy by the name the creator typed. */
export function requestSpawn(spotName: string): void {
  const shared = bus()
  const entry = shared.spots.get(stableId(zoneKey(spotName)))
  if (entry === undefined) {
    const known = spotNames()
    console.log(
      `[spawnBus] no spawn point is named '${spotName}'${known.length === 0 ? ' — this scene has none' : ` — the ones this scene has are: ${known.join(', ')}`}`
    )
    return
  }
  request(shared, entry)
}

/** This copy is done with: the server removes it for everyone. */
export function retireSpawned(entity: Entity): void {
  const marker = spawnedFrom(entity)
  if (marker === null) {
    console.log('[spawnBus] retireSpawned() was handed an entity no spawn point made')
    return
  }
  if (isServer()) {
    retireInstance(bus(), marker.instanceId, marker.prefab)
    return
  }
  void spawnRpc.call('retire', { key: marker.prefab, instance: marker.instanceId }).catch(() => {
    // a lost retire is a copy that lingers, never a throw inside a script
  })
}

/** Every registered spawn point, in the creator's spelling. */
export function spotNames(): string[] {
  return [...bus().spots.values()].map((entry) => entry.name)
}

// --- asking ---------------------------------------------------------------

function request(shared: SpawnHub, entry: SpotEntry): void {
  if (!ready(shared, entry)) {
    if (!entry.notReadyLogged) {
      entry.notReadyLogged = true
      console.log(`[spawnBus] '${entry.name}' cannot make a copy yet — the game server is still waking up`)
    }
    return
  }
  entry.notReadyLogged = false
  if (isServer()) {
    // the drip and the scene-load spawn run here, and they are not rate limited:
    // every server-side report shares one bucket, so limiting it would throttle
    // the server against itself
    report(mintLocal(shared, entry, Date.now()), entry)
    return
  }
  requestCounter += 1
  const nonce = `${SESSION}:${requestCounter}`
  void spawnRpc
    .call<{ ok?: unknown; reason?: unknown }>('ask', { spot: entry.spotId, nonce })
    .then((verdict) => {
      if (verdict.ok === false) console.log(`[spawnBus] '${entry.name}':`, verdict.reason)
    })
    .catch(() => {
      // a lost request is a lost press, never a throw inside a script
    })
}

function ready(shared: SpawnHub, entry: SpotEntry): boolean {
  if (serverLifeState() !== 'running') return false
  return shared.ledgers.get(entry.ledgerKey)?.ledger.isSynced() ?? false
}

function report(verdict: { ok: boolean; reason?: string }, entry: SpotEntry): void {
  if (verdict.ok) return
  console.log(`[spawnBus] '${entry.name}':`, verdict.reason)
}

// --- the ledger, both sides -----------------------------------------------

function bindLedger(shared: SpawnHub, key: string): LedgerBinding {
  const existing = shared.ledgers.get(key)
  if (existing !== undefined) return existing
  const created: LedgerBinding = { key, ledger: outcomes(key), fold: emptyFold(), lastSeq: 0, armed: false }
  shared.ledgers.set(key, created)
  // A spot that binds after another spot already drove the catch-up walk gets no
  // replay of its own — the walk delivered to the handlers that existed then. The
  // history collected so far is folded here instead; applyEntry is idempotent, so
  // an entry that arrives both ways lands once.
  for (const entry of created.ledger.snapshot()) note(created, entry)
  created.ledger.onOutcome((entry) => note(created, entry))
  const side = shared.server
  if (side !== null && side.blindBase > 0 && created.lastSeq === 0) rehydrate(shared, key, [], side.blindBase)
  return created
}

function note(binding: LedgerBinding, entry: OutcomeEntry): void {
  if (!isServer() && binding.lastSeq > 0 && entry.seq > binding.lastSeq + 1) {
    // The sequence skipped: a restarted server, or a history older than the replay
    // window. What we hold is no longer a prefix of the truth, so it is rebuilt
    // from this delivery — which is the full alive set, since a jump only ever
    // arrives through a fast-forward.
    binding.fold = emptyFold()
  }
  if (entry.seq > binding.lastSeq) binding.lastSeq = entry.seq
  applyEntry(binding.fold, entry)
}

function armValidators(shared: SpawnHub, binding: LedgerBinding): void {
  if (binding.armed || !isServer()) return
  binding.armed = true
  // Armed once per LEDGER KEY, never once per spot: validators are last-writer-wins
  // per kind, so a second spot on the same prefab would silently discard the first
  // closure. Every per-spot number is read out of the registry, never captured.
  binding.ledger.validate(SPAWN_KIND, (payload, from) => {
    if (from !== 'server') return refuse(binding, 'spawn-forged', 'a copy can only be minted by the server')
    const spotId = Math.floor(numberOf(payload.amount, -1))
    const entry = shared.spots.get(spotId)
    if (entry === undefined) return refuse(binding, 'spawn-unknown', 'that spawn point is not in this scene')
    if (hasSeen(binding.fold, payload.instanceId)) {
      return refuse(binding, 'spawn-seen', 'that copy has already existed once')
    }
    if (aliveCount(binding.fold, spotId) >= entry.atMostAtOnce) {
      return refuse(binding, 'spawn-full', `'${entry.name}' already has as many copies as it allows`)
    }
    return { ok: true, value: spotId }
  })
  binding.ledger.validate(DESPAWN_KIND, (payload, from) => {
    if (from !== 'server') return refuse(binding, 'despawn-forged', 'a copy can only be removed by the server')
    const spot = spotOfInstance(binding.fold, payload.instanceId)
    if (spot === null || !isAlive(binding.fold, payload.instanceId)) {
      return refuse(binding, 'despawn-gone', 'that copy is not here')
    }
    return { ok: true, value: spot }
  })
  binding.ledger.validate(RESTART_KIND, (_payload, from) =>
    from === 'server' ? { ok: true, value: 0 } : refuse(binding, 'restart-forged', 'server-only')
  )
}

function refuse(binding: LedgerBinding, tag: string, reason: string): { ok: false; reason: string } {
  // once per reason: a validator that refuses every frame would bury the log, and
  // one that refuses invisibly is the failure the ledger was built to make loud
  const key = `${binding.key}:${tag}`
  const shared = bus()
  if (shared.server !== null && !shared.server.rejections.has(key)) {
    shared.server.rejections.add(key)
    console.log(`[spawnBus] refused a '${tag.split('-')[0]}': ${reason}`)
  }
  return { ok: false, reason }
}

// --- the server ------------------------------------------------------------

function join(shared: SpawnHub): void {
  if (shared.lifeStarted) return
  shared.lifeStarted = true
  startServerLife(PARTICIPANT)
  if (isServer()) startServerSide(shared)
}

function startServerSide(shared: SpawnHub): void {
  if (shared.server !== null) return
  const store = serverState<SavedSpawns>({ key: STATE_KEY, defaults: emptySaved, persist: true })
  const side: ServerSide = {
    store,
    restored: false,
    dirty: false,
    lastFlushMs: 0,
    nextInstanceId: 0,
    blindBase: 0,
    expiries: new Map(),
    nonces: new Map(),
    askedAtMs: new Map(),
    rejections: new Set()
  }
  shared.server = side
  installHandlers(shared)
  void store
    .restore()
    .catch(() => store.restore())
    .then(() => adopt(shared, side))
    .catch((error) => {
      // Twice-failed storage. Starting silently fresh would restart every ledger
      // sequence at 1, which surviving clients drop as already-seen — a press
      // that mints a copy nobody ever sees. Jumping the sequence far past any
      // realistic uptime turns that into an ordinary restart gap they repair.
      console.log('[spawnBus] could not read back what this server had spawned — restarting blind:', error)
      adoptBlind(shared, side)
    })
    .then(() => {
      side.restored = true
      // Last, always: a server that never answers leaves every client in "waking"
      // forever, and one that answers before this leaks ids it already minted.
      markServerReady(PARTICIPANT)
    })
}

// ~57 days of the busiest shipped walkthrough (720 entries/hour) stays under
// this, so a blind jump lands ahead of any sequence a surviving client holds.
const BLIND_SEQ_BASE = 1_000_000

function adoptBlind(shared: SpawnHub, side: ServerSide): void {
  side.blindBase = BLIND_SEQ_BASE
  for (const key of [...shared.ledgers.keys()]) {
    const binding = shared.ledgers.get(key)
    if (binding !== undefined && binding.lastSeq === 0) rehydrate(shared, key, [], BLIND_SEQ_BASE)
  }
}

function adopt(shared: SpawnHub, side: ServerSide): void {
  const saved = side.store.get()
  side.nextInstanceId = Math.max(0, Math.floor(numberOf(saved.nextInstanceId, 0)))
  for (const row of saved.nonces) {
    if (isRecord(row) && typeof row.nonce === 'string') side.nonces.set(row.nonce, Math.floor(numberOf(row.id, 0)))
  }
  const seqs = new Map<string, number>()
  for (const row of saved.lastSeqByKey) {
    if (isRecord(row) && typeof row.key === 'string') seqs.set(row.key, Math.floor(numberOf(row.seq, 0)))
  }
  const rows = new Map<string, SavedInstance[]>()
  for (const row of saved.alive) {
    if (!isRecord(row) || typeof row.key !== 'string') continue
    const parsed: SavedInstance = {
      id: Math.floor(numberOf(row.id, 0)),
      spot: Math.floor(numberOf(row.spot, 0)),
      key: row.key,
      until: numberOf(row.until, 0)
    }
    if (parsed.id <= 0) continue
    rows.set(parsed.key, [...(rows.get(parsed.key) ?? []), parsed])
    if (parsed.until > 0) side.expiries.set(parsed.id, parsed.until)
    seqs.set(parsed.key, seqs.get(parsed.key) ?? 0)
    side.nextInstanceId = Math.max(side.nextInstanceId, parsed.id)
  }
  for (const [key, seq] of seqs) rehydrate(shared, key, rows.get(key) ?? [], seq)
}

/**
 * Hand one ledger a synthetic history: a restart marker, then one spawn per copy
 * that was alive. The sequence continues from where it left off PLUS a gap, so a
 * client still holding seq 400 sees the numbers move forward — a sequence that
 * restarted at 1 would be dropped as already-seen and that client would never
 * hear from this server again.
 */
function rehydrate(shared: SpawnHub, key: string, rows: SavedInstance[], lastSeq: number): void {
  const binding = bindLedger(shared, key)
  const base = Math.max(0, lastSeq) + SEQ_RESTART_GAP
  const entries: OutcomeEntry[] = [{ seq: base, instanceId: 0, kind: RESTART_KIND, value: 0 }]
  for (const row of rows) {
    entries.push({ seq: base + entries.length, instanceId: row.id, kind: SPAWN_KIND, value: row.spot })
  }
  binding.ledger.fastForward(entries)
  binding.fold = emptyFold()
  for (const entry of entries) applyEntry(binding.fold, entry)
  binding.lastSeq = entries[entries.length - 1].seq
  armValidators(shared, binding)
  // One appended-and-broadcast entry, so a client that never disconnected notices
  // the gap and repairs it instead of waiting for the next press to reveal it.
  binding.ledger.report(RESTART_KIND, { instanceId: 0, amount: 0 })
}

function installHandlers(shared: SpawnHub): void {
  spawnRpc.handle('ask', (body, from) => {
    const ask = readAsk(body)
    if (ask === null) return { ok: false, reason: 'malformed request' }
    const side = shared.server
    if (side === null || !side.restored) return { ok: false, reason: 'the game server is still waking up' }
    // Idempotency first: the rpc layer resends the same body on a timeout, and an
    // answered nonce must come back with the id it already minted or one press
    // becomes two copies.
    const nonceKey = `${from}:${ask.nonce}`
    const already = side.nonces.get(nonceKey)
    if (already !== undefined) return { ok: true, instanceId: already }
    const entry = shared.spots.get(ask.spot)
    if (entry === undefined) return { ok: false, reason: 'that spawn point is not in this scene' }
    const now = Date.now()
    if (limited(side, `${from}|ask`, now)) return { ok: false, reason: 'that is too many requests at once' }
    const verdict = mintLocal(shared, entry, now)
    if (!verdict.ok || verdict.instanceId === undefined) return verdict
    remember(side, nonceKey, verdict.instanceId)
    return verdict
  })
  spawnRpc.handle('retire', (body, from) => {
    const retire = readRetire(body)
    if (retire === null) return { ok: false, reason: 'malformed request' }
    const side = shared.server
    if (side === null || !side.restored) return { ok: false, reason: 'the game server is still waking up' }
    if (limited(side, `${from}|retire`, Date.now())) return { ok: false, reason: 'that is too many requests at once' }
    retireInstance(shared, retire.instance, retire.key)
    return { ok: true }
  })
}

function mintLocal(
  shared: SpawnHub,
  entry: SpotEntry,
  nowMs: number
): { ok: boolean; instanceId?: number; reason?: string } {
  const side = shared.server
  if (side === null || !side.restored) return { ok: false, reason: 'the game server is still waking up' }
  const binding = bindLedger(shared, entry.ledgerKey)
  if (aliveCount(binding.fold, entry.spotId) >= entry.atMostAtOnce) {
    return { ok: false, reason: 'it already has as many copies as it allows' }
  }
  side.nextInstanceId += 1
  const instanceId = side.nextInstanceId
  if (entry.lifetimeMs > 0) side.expiries.set(instanceId, nowMs + entry.lifetimeMs)
  side.dirty = true
  // walks serve() → validator → append → broadcast; the validator is the authority
  binding.ledger.report(SPAWN_KIND, { instanceId, amount: entry.spotId })
  return { ok: true, instanceId }
}

function retireInstance(shared: SpawnHub, instanceId: number, key: string): void {
  const side = shared.server
  if (side === null) return
  side.expiries.delete(instanceId)
  side.dirty = true
  // An EXISTING binding only: the key arrives off the wire, and opening a ledger
  // for whatever a client names would let one spam this server into holding a
  // ledger — and persisting a sequence number — per made-up prefab id.
  const binding = shared.ledgers.get(key)
  if (binding === undefined || !isAlive(binding.fold, instanceId)) return
  binding.ledger.report(DESPAWN_KIND, { instanceId, amount: spotOfInstance(binding.fold, instanceId) ?? 0 })
}

function limited(side: ServerSide, bucket: string, nowMs: number): boolean {
  const last = side.askedAtMs.get(bucket) ?? 0
  if (nowMs - last < MIN_REQUEST_INTERVAL_MS) return true
  side.askedAtMs.set(bucket, nowMs)
  if (side.askedAtMs.size > MAX_NONCES) side.askedAtMs.delete([...side.askedAtMs.keys()][0])
  return false
}

function remember(side: ServerSide, nonceKey: string, instanceId: number): void {
  side.nonces.set(nonceKey, instanceId)
  while (side.nonces.size > MAX_NONCES) side.nonces.delete([...side.nonces.keys()][0])
  side.dirty = true
}

// --- the drivers ------------------------------------------------------------

function install(shared: SpawnHub): void {
  if (shared.installed) return
  shared.installed = true
  if (isServer()) {
    let waited = 0
    engine.addSystem(
      (dt: number) => {
        waited += dt
        if (waited < SWEEP_S) return
        waited = 0
        driveServer(shared, Date.now())
      },
      undefined,
      'runtime-spawnbus'
    )
    return
  }
  engine.addSystem(() => driveClient(shared), undefined, 'runtime-spawnbus')
}

function driveServer(shared: SpawnHub, nowMs: number): void {
  const side = shared.server
  if (side === null || !side.restored) return
  // Lifetimes are the server's, not each client's: N clients each running their
  // own timer would each remove the copy at a different moment, and only one of
  // them would be right. The deadline is absolute and persisted, so a copy with
  // ten seconds left does not get another ten because the server slept.
  for (const [instanceId, until] of [...side.expiries]) {
    if (nowMs < until) continue
    retireInstance(shared, instanceId, keyOf(shared, instanceId))
  }
  flush(shared, side, nowMs)
}

function keyOf(shared: SpawnHub, instanceId: number): string {
  for (const binding of shared.ledgers.values()) {
    if (spotOfInstance(binding.fold, instanceId) !== null) return binding.key
  }
  return ''
}

function driveClient(shared: SpawnHub): void {
  for (const entry of shared.spots.values()) {
    const binding = shared.ledgers.get(entry.ledgerKey)
    // The gate is materialisation only. Folding already happened, unconditionally,
    // as the walk delivered — this is the drain, the same shape the wave director
    // uses once its own catch-up lands.
    if (binding === undefined || !binding.ledger.isSynced()) continue
    const wanted = new Set(aliveIn(binding.fold, entry.spotId))
    for (const instanceId of wanted) {
      if (entry.live.has(instanceId)) continue
      const spawned = materialise(entry, instanceId)
      if (spawned === null) break
      entry.live.set(instanceId, spawned)
    }
    for (const [instanceId, spawned] of [...entry.live]) {
      if (wanted.has(instanceId)) continue
      entry.live.delete(instanceId)
      entry.pool.release(spawned)
    }
  }
}

function materialise(entry: SpotEntry, instanceId: number): Entity | null {
  const world = worldOf(entry.spot)
  const offset = scatterOffset(instanceId, effectiveScatter(entry.scatterRadius, entry.atMostAtOnce))
  // The init write replaces the clone's whole Transform, and the spot's world
  // scale must not leak into it — a spawner shrunk to a marker would shrink its
  // zombies. Position and rotation are the spot's; scale stays the prefab's own.
  const authoredRoot = snapshotRootComponent(entry.pool.prefab, TRANSFORM)
  const authored = localOf(isRecord(authoredRoot) ? authoredRoot : null)
  try {
    // A clone's own start() is creator code. Letting it throw out of a system would
    // abort the rest of the frame AND the CRDT flush, so one bad script would
    // freeze the scene rather than lose one copy.
    return entry.pool.acquire(instanceId, {
      [TRANSFORM]: {
        position: {
          x: world.position.x + offset.x,
          y: world.position.y,
          z: world.position.z + offset.z
        },
        rotation: world.rotation,
        scale: authored.scale
      }
    })
  } catch (error) {
    console.error(`[spawnBus] '${entry.name}' could not make a copy of ${entry.pool.prefab}:`, error)
    return null
  }
}

// --- persistence ------------------------------------------------------------

function flush(shared: SpawnHub, side: ServerSide, nowMs: number): void {
  if (!side.dirty || nowMs - side.lastFlushMs < FLUSH_MIN_MS) return
  side.dirty = false
  side.lastFlushMs = nowMs
  side.store.patch(snapshotState(shared, side))
  void side.store.flush().catch(() => {
    // a write that did not land leaves the store dirty, so the next flush retries
  })
}

function snapshotState(shared: SpawnHub, side: ServerSide): SavedSpawns {
  const alive: SavedInstance[] = []
  const lastSeqByKey: Array<{ key: string; seq: number }> = []
  for (const binding of shared.ledgers.values()) {
    lastSeqByKey.push({ key: binding.key, seq: binding.lastSeq })
    for (const [id, spot] of alivePairs(binding.fold)) {
      alive.push({ id, spot, key: binding.key, until: side.expiries.get(id) ?? 0 })
    }
  }
  return {
    nextInstanceId: side.nextInstanceId,
    alive,
    nonces: [...side.nonces].map(([nonce, id]) => ({ nonce, id })),
    lastSeqByKey
  }
}

function emptySaved(): SavedSpawns {
  return { nextInstanceId: 0, alive: [], nonces: [], lastSeqByKey: [] }
}

// --- placement --------------------------------------------------------------

/** The composed world transform of an entity, walking its parents to the scene root. */
function worldOf(entity: Entity): WorldTransform {
  return composeWorld(chainOf(entity).chain)
}

/**
 * The parent chain of an entity, ROOT-FIRST, and whether anything on it is a copy
 * some pool spawned — which is what makes a spawn point nested inside a spawnable
 * prefab detectable before it registers a second time under the same name.
 */
function chainOf(entity: Entity): { chain: LocalTransform[]; pooled: boolean } {
  const chain: LocalTransform[] = []
  const seen = new Set<number>()
  let pooled = false
  let current: Entity | null = entity
  for (let depth = 0; current !== null && depth < PARENT_DEPTH_MAX; depth++) {
    const id = Number(current)
    if (id === 0 || seen.has(id)) break
    seen.add(id)
    if (spawnedFrom(current) !== null) pooled = true
    const local = Transform.getOrNull(current)
    chain.push(localOf(local))
    const parent = local?.parent
    current = parent === undefined || Number(parent) === 0 ? null : parent
  }
  chain.reverse()
  return { chain, pooled }
}

function localOf(value: { position?: unknown; rotation?: unknown; scale?: unknown } | null): LocalTransform {
  const identity = identityTransform()
  if (value === null) return { ...identity, parent: 0 }
  const position = isRecord(value.position) ? value.position : {}
  const rotation = isRecord(value.rotation) ? value.rotation : {}
  const scale = isRecord(value.scale) ? value.scale : {}
  return {
    position: {
      x: numberOf(position.x, 0),
      y: numberOf(position.y, 0),
      z: numberOf(position.z, 0)
    },
    rotation: {
      x: numberOf(rotation.x, 0),
      y: numberOf(rotation.y, 0),
      z: numberOf(rotation.z, 0),
      w: numberOf(rotation.w, 1)
    },
    scale: {
      x: numberOf(scale.x, 1),
      y: numberOf(scale.y, 1),
      z: numberOf(scale.z, 1)
    },
    parent: 0
  }
}

/**
 * `atMostAtOnce` is a share of the pool, not a private allowance: the pool's max
 * is the real ceiling and every other consumer of that prefab draws from the same
 * one. Clamping loudly beats a spawn point that silently never reaches its number.
 */
function clampToPool(name: string, wanted: number, pool: Pool): number {
  const asked = Math.max(1, Math.floor(numberOf(wanted, 1)))
  if (asked <= pool.max) return asked
  console.log(
    `[spawnBus] '${name}' asks for ${asked} copies at once but '${pool.prefab}' only allows ${pool.max} — using ${pool.max}. Raise the prefab's copy limit in the Prefabs tab.`
  )
  return pool.max
}

// --- wire reading -----------------------------------------------------------

function readAsk(body: unknown): { spot: number; nonce: string } | null {
  if (!isRecord(body)) return null
  if (typeof body.spot !== 'number' || !Number.isFinite(body.spot)) return null
  if (typeof body.nonce !== 'string' || body.nonce === '') return null
  return { spot: Math.floor(body.spot), nonce: body.nonce }
}

function readRetire(body: unknown): { key: string; instance: number } | null {
  if (!isRecord(body)) return null
  if (typeof body.key !== 'string' || body.key === '') return null
  if (typeof body.instance !== 'number' || !Number.isFinite(body.instance)) return null
  return { key: body.key, instance: Math.floor(body.instance) }
}

function numberOf(value: unknown, fallback: number): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : fallback
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

// --- the shared bus ---------------------------------------------------------

function bus(): SpawnHub {
  const globals = globalThis as unknown as Record<string, unknown>
  const current = globals[BUS_KEY]
  if (isBus(current)) return current
  const created: SpawnHub = {
    spots: new Map<number, SpotEntry>(),
    ledgers: new Map<string, LedgerBinding>(),
    installed: false,
    lifeStarted: false,
    server: null
  }
  globals[BUS_KEY] = created
  return created
}

// Two prefabs bundle two copies of this file, so the classes differ and instanceof
// would reject the shared bus — shape is the only identity that survives (the
// zoneBus rule).
function isBus(value: unknown): value is SpawnHub {
  return (
    typeof value === 'object' &&
    value !== null &&
    'spots' in value &&
    value.spots instanceof Map &&
    'ledgers' in value &&
    value.ledgers instanceof Map &&
    'installed' in value &&
    typeof value.installed === 'boolean'
  )
}
