// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Spawn points by name. A Spawner registers itself under its entity's Name, and
// any other script sets it off with the same words the creator typed:
//
//   requestSpawn('Crate Spawner')   // a lever, a round script, an AI request
//
// Names match trimmed and case-insensitively (zoneKey), same as zones — two
// spellings of one name is a silent failure, so there is exactly one rule.
//
// The registry is anchored on globalThis rather than in module scope because
// every prefab bundles its OWN copy of this file: two module instances would be
// two disconnected registries.
import { type Entity } from '@dcl/sdk/ecs'
import { poolFor, spawnedFrom } from './spawner'
import { zoneKey } from './pure/zoneRegistry'

const KEY = '__dclSpawnPoints_v1'

/**
 * Claim a name. Refused (logged, never thrown) for a blank name or a name
 * already claimed — the first claimant keeps it, so a second Spawner spelled
 * the same way stands down instead of both answering one request.
 */
export function registerSpawnPoint(name: string, spawnOne: () => void): boolean {
  const key = zoneKey(name)
  if (key === '') {
    console.log('[Spawner] a spawn point needs a name — give this entity a Name in the hierarchy')
    return false
  }
  const points = registry()
  if (points.has(key)) {
    console.log(`[Spawner] two spawn points are both named '${name.trim()}' — rename one, only the first answers`)
    return false
  }
  points.set(key, spawnOne)
  return true
}

/** Ask a spawn point for a copy, by the name the creator typed. */
export function requestSpawn(name: string): void {
  const spawnOne = registry().get(zoneKey(name))
  if (spawnOne === undefined) {
    console.log(`[Spawner] no spawn point is named '${name.trim()}' — check the Spawner's Name in the hierarchy`)
    return
  }
  spawnOne()
}

/** Take one spawned copy away (a pickup that was collected). No-op for anything else. */
export function retireSpawned(entity: Entity): void {
  const from = spawnedFrom(entity)
  if (from === null) return
  poolFor(from.prefab)?.release(entity)
}

// Map is the host's own class, one identity for every module copy — safe to probe.
function registry(): Map<string, () => void> {
  const globals = globalThis as unknown as Record<string, unknown>
  const current = globals[KEY]
  if (current instanceof Map) return current as Map<string, () => void>
  const created = new Map<string, () => void>()
  globals[KEY] = created
  return created
}
