// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Drives a tween from the server clock so every player sees it in the same
// place at the same moment.
//
//   initTimeSync()                         // once, from your script's start()
//   driveShuttle(entity, plan)             // every frame, from update()
//
// Nothing about the platform is ever synced — no syncEntity, no messages, not
// one byte on the wire. Each peer independently derives the same answer from
// the same clock, which is cheaper AND more accurate than replicating a
// position, because a replicated position is always one round trip stale.
//
// Read the header of pure/tweenPhase.ts for why the schedule is derived rather
// than accumulated. Two rules in here are load-bearing and easy to undo:
//
//   1. NO isServer() FORK. The server runs this loop too. If you skip it there,
//      the server's own tween integrates to the end of its first leg, latches
//      "completed", and freezes forever — while every client keeps looping. The
//      server's collider is then permanently in the wrong place and nothing
//      reports an error.
//   2. NEVER WRITE TweenSequence. The SDK's sequence system would flip legs on
//      its own schedule and fight every seek this module makes.

import { SyncComponents, Tween, TweenState, TweenSequence, EasingFunction, type Entity } from '@dcl/sdk/ecs'
import { Vector3 } from '@dcl/sdk/math'
import { getServerTime, isTimeSyncReady } from './timeSync'
import {
  clampSeek,
  cycleMsOfLegs,
  easedAt,
  legPhaseAt,
  pathLegs,
  type Easing,
  type Leg,
  type PathMode
} from './pure/tweenPhase'

// The inspector's Transform-style param: a script constructor arg typed
// `Position` renders as XYZ fields and stores this shape. The offset is in the
// owning entity's local frame — metres from where the entity was placed.
export interface Position {
  x: number
  y: number
  z: number
}

export interface PathPlan {
  /**
   * The stops, in travel order — the first is where the platform rests.
   * Capture these ONCE, before the first tween runs.
   */
  stops: Vector3[]
  /** How the path repeats: back and forth, around the loop, or once. */
  mode: PathMode
  /** Ms between consecutive stops. */
  travelMs: number
  /** Ms the platform waits at each stop. */
  waitMs: number
  easing: Easing
  /** Shifts this platform along the shared cycle, to stagger a row of them. */
  offsetMs: number
  /**
   * Server-clock ms the cycle is anchored to. 0 (or absent) anchors to the
   * Unix epoch — the platform has conceptually always been running, so every
   * peer lands on the same phase with no messages at all. A platform brought
   * in at runtime ("the lift was called at T") anchors to that shared
   * timestamp instead: it starts its first leg at rest at T, and a peer who
   * joins later derives the same phase from the same fact. A 'once' path plays
   * a single run from its anchor and parks at the last stop.
   */
  sinceMs?: number
}

/** The two-stop plan `driveShuttle` takes — the common case, kept simple. */
export interface ShuttlePlan {
  from: Vector3
  to: Vector3
  travelMs: number
  waitMs: number
  easing: Easing
  offsetMs: number
  sinceMs?: number
}

// A correction is allowed to move the deck this far in one frame. The engine
// stops carrying a rider at 5 units and does not clamp — it drops them.
const MAX_SNAP_UNITS = 4

// Below this, a correction costs more than the error. One 30 Hz server frame is
// ~33 ms, so anything tighter would re-arm on ordinary sampling noise.
const DRIFT_TOLERANCE_MS = 60

// TweenState reports the tween's progress one CRDT round trip late, so a fresh
// arm always "looks" wrong for a tick or two. Wait it out before auditing.
const AUDIT_GRACE_MS = 250

interface DriveState {
  legKey: string
  armedAtMs: number
  prepared: boolean
}

const drives = new Map<number, DriveState>()

/**
 * Moves `entity` back and forth between two points, in phase with every other
 * player. Safe to call every frame; it only writes when something changed.
 */
export function driveShuttle(entity: Entity, plan: ShuttlePlan): void {
  drivePath(entity, pathPlanOf(plan))
}

function pathPlanOf(plan: ShuttlePlan): PathPlan {
  return {
    stops: [plan.from, plan.to],
    mode: 'back and forth',
    travelMs: plan.travelMs,
    waitMs: plan.waitMs,
    easing: plan.easing,
    offsetMs: plan.offsetMs,
    sinceMs: plan.sinceMs
  }
}

/**
 * Moves `entity` along its stops, in phase with every other player. Safe to
 * call every frame; it only writes when something changed.
 */
export function drivePath(entity: Entity, plan: PathPlan): void {
  const state = stateOf(entity)

  if (!state.prepared) {
    state.prepared = true
    // A sequence would re-arm legs behind our back.
    TweenSequence.deleteFrom(entity)
    // A synced entity would turn the renderer's tween writeback into a
    // per-tick Transform stream from the server that fights every client's
    // local tween — the position is derived, never replicated.
    if (SyncComponents.getOrNull(entity) !== null) {
      console.error(
        '[syncedTween] this entity is synced (syncEntity) — its platform will stream Transforms and fight the local tween. Drive an unsynced entity instead.'
      )
    }
  }

  if (plan.stops.length < 2) return
  const legs = pathLegs(plan.stops.length, plan.travelMs, plan.waitMs, plan.mode)
  if (cycleMsOfLegs(legs) <= 0) return

  // Until the clock lands, hold still at the start rather than run on a local
  // guess — a platform that jumps when sync arrives is worse than a late one.
  if (!isTimeSyncReady()) {
    if (state.legKey !== 'unsynced') {
      state.legKey = 'unsynced'
      park(entity, plan.stops[0])
    }
    return
  }

  const nowMs = getServerTime() + plan.offsetMs
  const phase = legPhaseAt(legs, nowMs, plan.sinceMs ?? 0, { cyclic: plan.mode !== 'once' })
  if (!phase) return

  const legKey = `${phase.index}@${phase.startedAtMs}`
  if (legKey !== state.legKey) {
    state.legKey = legKey
    state.armedAtMs = nowMs
    // A boundary arm cannot jump: the new leg starts where the old one ended.
    arm(entity, plan, phase.leg, phase.progress)
    return
  }

  if (!phase.leg.moving) return
  if (nowMs - state.armedAtMs < AUDIT_GRACE_MS) return

  const observed = TweenState.getOrNull(entity)?.currentTime
  if (observed === undefined) return

  const driftMs = Math.abs(phase.progress - observed) * phase.leg.durationMs
  if (driftMs <= DRIFT_TOLERANCE_MS) return

  state.armedAtMs = nowMs
  const pathUnits = Vector3.distance(stopOf(plan, phase.leg.from), stopOf(plan, phase.leg.to))
  arm(entity, plan, phase.leg, clampSeek(observed, phase.progress, pathUnits, MAX_SNAP_UNITS, plan.easing))
}

/** Where the platform is right now, on any peer, without reading the engine. */
export function shuttlePositionAt(plan: ShuttlePlan, atMs: number): Vector3 | null {
  return pathPositionAt(pathPlanOf(plan), atMs)
}

/** Where the platform is at any server timestamp, on any peer, engine-free. */
export function pathPositionAt(plan: PathPlan, atMs: number): Vector3 | null {
  if (plan.stops.length < 2) return null
  const legs = pathLegs(plan.stops.length, plan.travelMs, plan.waitMs, plan.mode)
  const phase = legPhaseAt(legs, atMs + plan.offsetMs, plan.sinceMs ?? 0, {
    cyclic: plan.mode !== 'once'
  })
  if (!phase) return null
  const start = stopOf(plan, phase.leg.from)
  const end = stopOf(plan, phase.leg.to)
  const travelled = phase.leg.moving ? easedAt(phase.progress, plan.easing) : 1
  return Vector3.add(start, Vector3.scale(Vector3.subtract(end, start), travelled))
}

export function forgetShuttle(entity: Entity): void {
  drives.delete(entity as number)
}

function stateOf(entity: Entity): DriveState {
  const existing = drives.get(entity as number)
  if (existing) return existing
  const created: DriveState = { legKey: '', armedAtMs: 0, prepared: false }
  drives.set(entity as number, created)
  return created
}

function stopOf(plan: PathPlan, stop: number): Vector3 {
  return plan.stops[Math.min(Math.max(stop, 0), plan.stops.length - 1)]
}

function arm(entity: Entity, plan: PathPlan, leg: Leg, progress: number): void {
  // A wait is a zero-length move at the stop, not an absent mode: a Tween whose
  // mode has no start/end applies as (0,0,0) and teleports the deck to the
  // scene origin, which is far enough to drop everyone standing on it.
  const start = stopOf(plan, leg.from)
  const end = stopOf(plan, leg.to)
  Tween.createOrReplace(entity, {
    mode: Tween.Mode.Move({ start, end }),
    duration: Math.max(1, leg.durationMs),
    easingFunction: plan.easing === 'smooth' ? EasingFunction.EF_EASEQUAD : EasingFunction.EF_LINEAR,
    currentTime: leg.moving ? progress : 1,
    playing: leg.moving
  })
}

function park(entity: Entity, at: Vector3): void {
  Tween.createOrReplace(entity, {
    mode: Tween.Mode.Move({ start: at, end: at }),
    duration: 1000,
    easingFunction: EasingFunction.EF_LINEAR,
    currentTime: 1,
    playing: false
  })
}
