// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Names the version of this build's runtime module set. Every prefab authored
// against it records it as `minRuntime` in its data.json, and the editor reads it
// off this master to refuse a prefab that needs a newer build than this one
// (packages/ui/src/prefabs/runtime-gate.ts).
// The one master no project gets a copy of: vendoring writes the closure of the
// modules a scene's scripts import, nothing imports this file, and a copy of it
// would only report the build that last refreshed it rather than the one a scene
// was authored on.
// Bumping it is enforced: scripts/sync-runtime-modules.mjs digests every other
// master into runtime-digest.json and refuses to record a changed digest under an
// unchanged version.
export const RUNTIME_VERSION = '0.3.1'
