// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Bumped whenever any runtime module changes; written into scenes alongside
// the modules a prefab carries, so stale copies are detectable.
export const RUNTIME_VERSION = '0.2.0'
