import { describe, expect, it } from 'vitest'
import { gameConfigProblems, renderGameConfig } from './codegen'
import { defaultGameConfig, type GameConfigValue } from './normalize'

const EMPTY: GameConfigValue = { version: 0, tables: [], values: [] }

describe('renderGameConfig', () => {
  it('emits the §3.8 accessor shape', () => {
    const value: GameConfigValue = {
      version: 3,
      tables: [
        {
          name: 'waves',
          columns: [
            { name: 'wave', kind: 'number' },
            { name: 'count', kind: 'number' },
            { name: 'interval', kind: 'number' },
            { name: 'speedMult', kind: 'number' }
          ],
          rows: [{ key: '', cells: ['1', '6', '2.5', '1'] }]
        },
        { name: 'zombie', columns: [{ name: 'value', kind: 'number' }], rows: [{ key: 'hp', cells: ['40'] }, { key: 'biteDamage', cells: ['8'] }] },
        { name: 'weapons', columns: [{ name: 'value', kind: 'number' }], rows: [{ key: 'gunDamage', cells: ['12'] }, { key: 'fireRate', cells: ['4'] }] }
      ],
      values: [{ name: 'WINNER_POINTS', kind: 'number', value: '100' }]
    }
    expect(renderGameConfig(value)).toBe(
      `// GENERATED by the Decentraland Creator Hub editor. Do not edit.
// Source of truth: the Game Config component on the scene root.

export interface WavesRow { readonly wave: number; readonly count: number; readonly interval: number; readonly speedMult: number }

export const gameConfig = {
  version: 3,
  waves: [
    { wave: 1, count: 6, interval: 2.5, speedMult: 1 },
  ] as readonly WavesRow[],
  zombie: { hp: 40, biteDamage: 8 },
  weapons: { gunDamage: 12, fireRate: 4 },
  WINNER_POINTS: 100
} as const

export type GameConfig = typeof gameConfig

// prefab-folder scripts cannot import this path; they read this bag by shape
;(globalThis as unknown as Record<string, unknown>).__dclGameConfig_v1 = gameConfig
`
    )
  })

  it('renders an empty config without interfaces', () => {
    expect(renderGameConfig(EMPTY)).toBe(
      `// GENERATED by the Decentraland Creator Hub editor. Do not edit.
// Source of truth: the Game Config component on the scene root.

export const gameConfig = {
  version: 0
} as const

export type GameConfig = typeof gameConfig

// prefab-folder scripts cannot import this path; they read this bag by shape
;(globalThis as unknown as Record<string, unknown>).__dclGameConfig_v1 = gameConfig
`
    )
  })

  it('keeps a keyed multi-column table as a record of row objects', () => {
    const text = renderGameConfig({
      version: 1,
      tables: [
        {
          name: 'tiers',
          columns: [{ name: 'cost', kind: 'number' }, { name: 'unlocked', kind: 'boolean' }],
          rows: [{ key: 'bronze', cells: ['20', 'true'] }, { key: 'gold', cells: ['80', 'false'] }]
        }
      ],
      values: []
    })
    expect(text).toContain('  tiers: {\n    bronze: { cost: 20, unlocked: true },\n    gold: { cost: 80, unlocked: false },\n  }')
    expect(text).not.toContain('interface')
  })

  it('quotes string cells and non-identifier names', () => {
    const text = renderGameConfig({
      version: 1,
      tables: [{ name: 'copy', columns: [{ name: 'win text', kind: 'string' }], rows: [{ key: '', cells: ['You "won"'] }] }],
      values: [{ name: 'max-players', kind: 'number', value: '5' }]
    })
    expect(text).toContain('readonly "win text": string')
    expect(text).toContain('{ "win text": "You \\"won\\"" }')
    expect(text).toContain('"max-players": 5')
  })

  it('drops a reserved or duplicated name instead of shadowing version', () => {
    const text = renderGameConfig({
      version: 5,
      tables: [
        { name: 'version', columns: [{ name: 'a', kind: 'number' }], rows: [] },
        { name: 'dup', columns: [{ name: 'a', kind: 'number' }], rows: [{ key: '', cells: ['1'] }] },
        { name: 'dup', columns: [{ name: 'b', kind: 'number' }], rows: [{ key: '', cells: ['2'] }] }
      ],
      values: [{ name: 'dup', kind: 'number', value: '9' }]
    })
    expect(text).toContain('version: 5')
    expect(text.match(/ {2}dup:/g)).toHaveLength(1)
    expect(text).toContain('{ a: 1 }')
    expect(text).not.toContain('{ b: 2 }')
  })

  it('gives each array table its own row interface, deduped by name', () => {
    const text = renderGameConfig({
      version: 0,
      tables: [
        { name: 'a-b', columns: [{ name: 'x', kind: 'number' }], rows: [] },
        { name: 'a b', columns: [{ name: 'y', kind: 'number' }], rows: [] }
      ],
      values: []
    })
    expect(text).toContain('export interface ABRow { readonly x: number }')
    expect(text).toContain('export interface ABRow2 { readonly y: number }')
    expect(text).toContain('"a-b": [] as readonly ABRow[]')
    expect(text).toContain('"a b": [] as readonly ABRow2[]')
  })

  it('breaks a wide keyed single-column table onto its own lines', () => {
    const rows = ['alpha', 'bravo', 'charlie', 'delta', 'echo', 'foxtrot', 'golf', 'hotel'].map((key) => ({ key, cells: ['1000'] }))
    const text = renderGameConfig({ version: 0, tables: [{ name: 'wide', columns: [{ name: 'value', kind: 'number' }], rows }], values: [] })
    expect(text).toContain('  wide: {\n    alpha: 1000,')
  })

  it('skips unnamed columns but keeps the remaining cells aligned', () => {
    const text = renderGameConfig({
      version: 0,
      tables: [
        {
          name: 't',
          columns: [{ name: '', kind: 'number' }, { name: 'b', kind: 'number' }],
          rows: [{ key: '', cells: ['1', '2'] }]
        }
      ],
      values: []
    })
    expect(text).toContain('{ b: 2 }')
  })

  it('is deterministic and ends with a newline', () => {
    const value = defaultGameConfig()
    expect(renderGameConfig(value)).toBe(renderGameConfig(value))
    expect(renderGameConfig(value).endsWith('\n')).toBe(true)
  })

  it('emits nothing invalid for the seeded default config', () => {
    const text = renderGameConfig(defaultGameConfig())
    expect(text).toContain('zombie: { hp: 40, biteDamage: 8, biteCooldown: 1.2, pointsPerKill: 5 }')
    expect(text).toContain('WINNER_POINTS: 100')
  })
})

describe('gameConfigProblems', () => {
  it('is silent on the seeded default config', () => {
    expect(gameConfigProblems(defaultGameConfig())).toEqual([])
  })

  it('names everything the emitter drops', () => {
    const problems = gameConfigProblems({
      version: 0,
      tables: [
        { name: '', columns: [], rows: [] },
        { name: 'version', columns: [], rows: [] },
        { name: 'dup', columns: [{ name: 'a', kind: 'number' }], rows: [] },
        { name: 'dup', columns: [{ name: 'a', kind: 'number' }], rows: [] },
        { name: 'holes', columns: [{ name: '', kind: 'number' }], rows: [] },
        { name: 'twice', columns: [{ name: 'a', kind: 'number' }], rows: [{ key: 'k', cells: ['1'] }, { key: 'k', cells: ['2'] }] }
      ],
      values: [{ name: '', kind: 'number', value: '1' }, { name: 'dup', kind: 'number', value: '1' }]
    })
    expect(problems).toEqual([
      'a table has no name and was skipped',
      'table "version" uses the reserved name "version" and was skipped',
      'table "dup" is defined twice; the later one was skipped',
      'table "holes" has an unnamed column; it is missing from every row',
      'table "twice" has two rows named "k"; the later one was skipped',
      'a value has no name and was skipped',
      'value "dup" collides with an earlier entry and was skipped'
    ])
  })

  it('reports bad cells with their table and column', () => {
    const problems = gameConfigProblems({
      version: 0,
      tables: [{ name: 'waves', columns: [{ name: 'count', kind: 'number', min: 0 }], rows: [{ key: '', cells: ['-3'] }] }],
      values: []
    })
    expect(problems).toEqual(['waves.count: below the minimum (0)'])
  })
})
