// Renders `src/scripts/game-config.ts` — the ONE accessor every script reads a
// tuned number through. Pure: text in, text out, no fs and no data layer, so the
// golden test can diff it byte-for-byte.
//
// Shape rules (contract §3.8):
//  - a table whose rows all carry a name generates as a record keyed by that
//    name; an unnamed-row table stays an array with a `<Table>Row` interface
//  - a keyed table with exactly one column collapses to `name: value`, which is
//    what makes `gameConfig.zombie.hp` read like a constant instead of a row
//  - `version` is the `configVersion` a plan tuple pins, so it is reserved: a
//    table or value called `version` is dropped rather than shadowing it
//
// The file also republishes itself on `globalThis.__dclGameConfig_v1`. A prefab
// folder is self-contained by rule, so a kit script cannot import this path —
// it reads the bag by shape instead, the same convention zoneBus uses. The
// import stays the way scene scripts read config; the global is the only bridge
// a prefab has, and without it every kit prefab silently runs on its defaults.
import {
  cellProblem,
  isKeyedTable,
  parseCell,
  type ConfigColumnDef,
  type ConfigKind,
  type ConfigRow,
  type ConfigTable,
  type GameConfigValue
} from './normalize'

const HEADER = [
  '// GENERATED by the Decentraland Creator Hub editor. Do not edit.',
  '// Source of truth: the Game Config component on the scene root.'
]

const RESERVED = new Set(['version'])
/** the bag a prefab-folder script reads config through — see the header */
export const GAME_CONFIG_GLOBAL = '__dclGameConfig_v1'
const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/
// keyed single-column tables inline until they stop fitting on a panel-wide line
const INLINE_LIMIT = 96

function isIdentifier(name: string): boolean {
  return IDENTIFIER.test(name)
}

function key(name: string): string {
  return isIdentifier(name) ? name : JSON.stringify(name)
}

function numberLiteral(value: number): string {
  return Object.is(value, -0) ? '0' : String(value)
}

function literal(cell: string, kind: ConfigKind): string {
  const parsed = parseCell(cell, kind)
  if (typeof parsed === 'number') return numberLiteral(parsed)
  if (typeof parsed === 'boolean') return parsed ? 'true' : 'false'
  return JSON.stringify(parsed)
}

function pascal(name: string): string {
  const parts = name.split(/[^A-Za-z0-9]+/).filter((p) => p !== '')
  const joined = parts.map((p) => p[0].toUpperCase() + p.slice(1)).join('')
  return joined === '' || /^[0-9]/.test(joined) ? `T${joined}` : joined
}

// Unnamed columns are skipped on emission, but cells stay index-aligned with the
// full column list, so the cell lookup keeps the original position.
function rowObject(row: ConfigRow, columns: ConfigColumnDef[]): string {
  const fields = columns
    .map((column, i) => ({ column, i }))
    .filter((entry) => entry.column.name !== '')
    .map((entry) => `${key(entry.column.name)}: ${literal(row.cells[entry.i] ?? '', entry.column.kind)}`)
  return fields.length === 0 ? '{}' : `{ ${fields.join(', ')} }`
}

function rowInterface(name: string, columns: ConfigColumnDef[]): string {
  const fields = columns
    .filter((column) => column.name !== '')
    .map((column) => `readonly ${key(column.name)}: ${column.kind}`)
  return `export interface ${name} { ${fields.join('; ')} }`
}

/** first-wins dedupe: two rows sharing a name would silently drop one at runtime */
function uniqueKeyedRows(table: ConfigTable): ConfigRow[] {
  const seen = new Set<string>()
  return table.rows.filter((row) => {
    const name = row.key.trim()
    if (seen.has(name)) return false
    seen.add(name)
    return true
  })
}

function renderScalarTable(table: ConfigTable): string {
  const column = table.columns[0]
  const pairs = uniqueKeyedRows(table).map((row) => `${key(row.key.trim())}: ${literal(row.cells[0] ?? '', column.kind)}`)
  if (pairs.length === 0) return '{}'
  const inline = `{ ${pairs.join(', ')} }`
  if (inline.length <= INLINE_LIMIT) return inline
  return ['{', ...pairs.map((p) => `    ${p},`), '  }'].join('\n')
}

function renderRecordTable(table: ConfigTable): string {
  const rows = uniqueKeyedRows(table)
  if (rows.length === 0) return '{}'
  const lines = rows.map((row) => `    ${key(row.key.trim())}: ${rowObject(row, table.columns)},`)
  return ['{', ...lines, '  }'].join('\n')
}

function renderArrayTable(table: ConfigTable, annotation: string): string {
  if (table.rows.length === 0) return `[]${annotation}`
  const lines = table.rows.map((row) => `    ${rowObject(row, table.columns)},`)
  return ['[', ...lines, `  ]${annotation}`].join('\n')
}

interface Emitted {
  interfaces: string[]
  entries: string[]
}

function emit(value: GameConfigValue): Emitted {
  const interfaces: string[] = []
  const entries: string[] = []
  const taken = new Set(RESERVED)
  const interfaceNames = new Set<string>()

  for (const table of value.tables) {
    const name = table.name.trim()
    if (name === '' || taken.has(name)) continue
    taken.add(name)
    const usable = table.columns.filter((column) => column.name !== '')
    if (isKeyedTable(table) && table.columns.length === 1 && usable.length === 1) {
      entries.push(`  ${key(name)}: ${renderScalarTable(table)}`)
      continue
    }
    if (isKeyedTable(table)) {
      entries.push(`  ${key(name)}: ${renderRecordTable(table)}`)
      continue
    }
    if (usable.length === 0) {
      entries.push(`  ${key(name)}: []`)
      continue
    }
    let rowType = `${pascal(name)}Row`
    let n = 2
    while (interfaceNames.has(rowType)) rowType = `${pascal(name)}Row${n++}`
    interfaceNames.add(rowType)
    interfaces.push(rowInterface(rowType, table.columns))
    entries.push(`  ${key(name)}: ${renderArrayTable(table, ` as readonly ${rowType}[]`)}`)
  }

  for (const scalar of value.values) {
    const name = scalar.name.trim()
    if (name === '' || taken.has(name)) continue
    taken.add(name)
    entries.push(`  ${key(name)}: ${literal(scalar.value, scalar.kind)}`)
  }

  return { interfaces, entries }
}

/**
 * Generation-time lint, mirroring exactly what `emit` drops. Every entry names
 * something the creator authored that will NOT appear in the accessor — silence
 * there is the failure mode ("I typed it in the table and the script can't see
 * it"). All warnings: none of them can corrupt the emitted file.
 */
export function gameConfigProblems(value: GameConfigValue): string[] {
  const problems: string[] = []
  const taken = new Set(RESERVED)
  for (const table of value.tables) {
    const name = table.name.trim()
    if (name === '') {
      problems.push('a table has no name and was skipped')
      continue
    }
    if (RESERVED.has(name)) {
      problems.push(`table "${name}" uses the reserved name "version" and was skipped`)
      continue
    }
    if (taken.has(name)) {
      problems.push(`table "${name}" is defined twice; the later one was skipped`)
      continue
    }
    taken.add(name)
    if (table.columns.some((column) => column.name === '')) {
      problems.push(`table "${name}" has an unnamed column; it is missing from every row`)
    }
    if (isKeyedTable(table)) {
      const seen = new Set<string>()
      for (const row of table.rows) {
        const rowKey = row.key.trim()
        if (seen.has(rowKey)) problems.push(`table "${name}" has two rows named "${rowKey}"; the later one was skipped`)
        seen.add(rowKey)
      }
    }
    for (const row of table.rows) {
      table.columns.forEach((column, i) => {
        const problem = cellProblem(row.cells[i] ?? '', column)
        if (problem !== null) problems.push(`${name}.${column.name}: ${problem}`)
      })
    }
  }
  for (const scalar of value.values) {
    const name = scalar.name.trim()
    if (name === '') {
      problems.push('a value has no name and was skipped')
      continue
    }
    if (taken.has(name)) {
      problems.push(`value "${name}" has the same name as an earlier entry and was skipped`)
      continue
    }
    taken.add(name)
  }
  return problems
}

export function renderGameConfig(value: GameConfigValue): string {
  const { interfaces, entries } = emit(value)
  const body = [`  version: ${numberLiteral(Math.trunc(value.version))}`, ...entries].join(',\n')
  const lines = [...HEADER, '']
  if (interfaces.length > 0) lines.push(...interfaces, '')
  lines.push(
    'export const gameConfig = {',
    body,
    '} as const',
    '',
    'export type GameConfig = typeof gameConfig',
    '',
    '// prefab-folder scripts cannot import this path; they read this bag by shape',
    `;(globalThis as unknown as Record<string, unknown>).${GAME_CONFIG_GLOBAL} = gameConfig`
  )
  return `${lines.join('\n')}\n`
}
