// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// What the spawn ledger MEANS, folded: which copies each spawn point currently
// has alive, and which instance ids have ever existed anywhere.
//
// The ledger is a sequence of `spawn` / `despawn` entries whose `value` carries
// the spawn point's id. Folding is deliberately total and idempotent: the same
// entry may arrive twice (a broadcast plus the catch-up walk that replays it),
// and a client that registers a second spawn point after the walk already ran
// folds the ledger's snapshot instead of a replay. Neither may double-count, so
// `everSeen` — not the alive set — decides whether a spawn is new.
//
// It also decides RESURRECTION: an instance id that has ever been spawned can
// never be spawned again, which is what makes a retried request harmless even
// if it reaches the validator twice with the same minted id.

export interface OutcomeEntryLike {
  instanceId: number
  kind: string
  /** the spawn point's id — what the validator returns as the entry's value */
  value: number
}

export interface SpawnFold {
  /** spot id → instance ids currently alive at it */
  aliveBySpot: Map<number, Set<number>>
  /** instance id → the spot that made it; kept after a despawn so a late entry still resolves */
  spotOf: Map<number, number>
  /** every instance id this fold has admitted. Never shrinks. */
  everSeen: Set<number>
}

export const SPAWN_KIND = 'spawn'
export const DESPAWN_KIND = 'despawn'

export function emptyFold(): SpawnFold {
  return { aliveBySpot: new Map(), spotOf: new Map(), everSeen: new Set() }
}

export function applyEntry(fold: SpawnFold, entry: OutcomeEntryLike): void {
  if (entry.kind === SPAWN_KIND) {
    // a replay and a resurrection are the same shape here, and both are no-ops
    if (fold.everSeen.has(entry.instanceId)) return
    fold.everSeen.add(entry.instanceId)
    fold.spotOf.set(entry.instanceId, entry.value)
    aliveSet(fold, entry.value).add(entry.instanceId)
    return
  }
  if (entry.kind !== DESPAWN_KIND) return
  const spot = fold.spotOf.get(entry.instanceId)
  // a despawn whose spawn fell off the replay window names nothing to remove
  if (spot === undefined) return
  aliveSet(fold, spot).delete(entry.instanceId)
}

export function foldEntries(entries: readonly OutcomeEntryLike[]): SpawnFold {
  const fold = emptyFold()
  for (const entry of entries) applyEntry(fold, entry)
  return fold
}

/** Ascending, so two clients drain the same set in the same order. */
export function aliveIn(fold: SpawnFold, spotId: number): number[] {
  return [...(fold.aliveBySpot.get(spotId) ?? [])].sort((a, b) => a - b)
}

export function aliveCount(fold: SpawnFold, spotId: number): number {
  return fold.aliveBySpot.get(spotId)?.size ?? 0
}

export function hasSeen(fold: SpawnFold, instanceId: number): boolean {
  return fold.everSeen.has(instanceId)
}

/** The spot that made an instance, or null for one this fold never admitted. */
export function spotOfInstance(fold: SpawnFold, instanceId: number): number | null {
  return fold.spotOf.get(instanceId) ?? null
}

export function isAlive(fold: SpawnFold, instanceId: number): boolean {
  const spot = fold.spotOf.get(instanceId)
  return spot !== undefined && (fold.aliveBySpot.get(spot)?.has(instanceId) ?? false)
}

/** Every live instance, as [instanceId, spotId] pairs — the shape the server persists. */
export function alivePairs(fold: SpawnFold): Array<[number, number]> {
  const pairs: Array<[number, number]> = []
  for (const [spot, ids] of fold.aliveBySpot) {
    for (const id of [...ids].sort((a, b) => a - b)) pairs.push([id, spot])
  }
  return pairs.sort((a, b) => a[0] - b[0])
}

function aliveSet(fold: SpawnFold, spotId: number): Set<number> {
  const existing = fold.aliveBySpot.get(spotId)
  if (existing !== undefined) return existing
  const created = new Set<number>()
  fold.aliveBySpot.set(spotId, created)
  return created
}
