import { describe, it, expect } from 'vitest'
import {
  SPAWNER_COMPONENTS_CONTRACT,
  exportShape,
  moduleIdentifier,
  prefabRefParams,
  relativeImport,
  renderSpawnables,
  type SpawnableSource
} from './codegen'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { readPrefabFile } from './builtin-fixtures'
import { ALLOWED_COMPONENTS } from '@scene/allowed-components'
import type { PrefabComposite, PrefabData } from './format'

const ECS_DECLARATIONS = ['dist/index.d.ts', 'dist/components/generated/global.gen.d.ts']

/** Every component @dcl/sdk/ecs declares a const export for, read off the installed pin. */
function sdkComponentDeclarations(): Set<string> {
  const names = new Set<string>()
  for (const rel of ECS_DECLARATIONS) {
    const file = fileURLToPath(new URL(`../../../../node_modules/@dcl/ecs/${rel}`, import.meta.url))
    if (!existsSync(file)) throw new Error(`@dcl/ecs is not installed — cannot check ${rel}`)
    for (const m of readFileSync(file, 'utf8').matchAll(/export declare const (\w+):/g)) names.add(m[1])
  }
  return names
}

const BRAIN = 'custom/zombie_basic/scripts/zombie-brain.ts'
const BRAIN_SOURCE = [
  "import { type Entity } from '@dcl/sdk/ecs'",
  'export class ZombieBrain {',
  '  constructor(public src: string, public entity: Entity, public speed: number = 2.5) {}',
  '  start(): void {}',
  '}'
].join('\n')

function prefab(over: Partial<PrefabData> & { id: string; name: string }): PrefabData {
  return { category: 'custom', tags: [], ...over }
}

const zombieComposite = (): PrefabComposite => ({
  version: 1,
  components: [
    { name: 'core::Transform', data: { '0': { json: { position: { x: 0, y: 0, z: 0 }, parent: 0 } } } },
    { name: 'core-schema::Name', data: { '0': { json: { value: 'Zombie' } } } },
    {
      name: 'asset-packs::Script',
      data: {
        '0': {
          json: {
            value: [
              {
                path: '{assetPath}/scripts/zombie-brain.ts',
                priority: 0,
                layout: '{"params":{"speed":{"type":"number","value":2.5}},"actions":[]}'
              }
            ]
          }
        }
      }
    }
  ]
})

const zombie = (): SpawnableSource => ({
  folder: 'custom/zombie_basic',
  data: prefab({ id: 'zombie-uuid', name: 'Zombie Basic', spawnable: { max: 64 } }),
  composite: zombieComposite()
})

const rig = (): SpawnableSource => ({
  folder: 'custom/player_rig',
  data: prefab({ id: 'rig-uuid', name: 'Player Rig', spawnable: { max: 32, instancing: 'perPlayer' } }),
  composite: {
    version: 1,
    components: [{ name: 'core::Transform', data: { '0': { json: { position: { x: 0, y: 0, z: 0 } } } } }]
  }
})

const render = (prefabs: SpawnableSource[], scripts: Record<string, string> = { [BRAIN]: BRAIN_SOURCE }) =>
  renderSpawnables({ prefabs, scripts })

describe('import specifiers and identifiers', () => {
  it('points src/scripts at the prefab folder copy', () => {
    expect(relativeImport('src/scripts', BRAIN)).toBe('../../custom/zombie_basic/scripts/zombie-brain')
    expect(relativeImport('src/scripts', 'src/scripts/runtime/spawner.ts')).toBe('./runtime/spawner')
  })

  it('derives a stable, collision-free namespace identifier', () => {
    expect(moduleIdentifier(BRAIN)).toBe('script_custom_zombie_basic_scripts_zombie_brain')
  })
})

describe('the generated registry', () => {
  it('emits the shape the runtime and the build both depend on', () => {
    const { text, problems, blocking } = render([zombie()])
    expect(problems).toEqual([])
    expect(blocking).toBe(false)
    expect(text.startsWith('// GENERATED by Decentraland Studio. Do not edit.\n')).toBe(true)
    expect(text).toContain("import { registerSpawnables, type PrefabSnapshot } from './runtime/spawner'")
    expect(text).toContain(
      "import * as script_custom_zombie_basic_scripts_zombie_brain from '../../custom/zombie_basic/scripts/zombie-brain'"
    )
    expect(text).toContain('export type PrefabRef = string & { readonly __prefabRef: unique symbol }')
    expect(text).toContain("  ZombieBasic: 'zombie-uuid' as PrefabRef")
    expect(text).toContain('module: script_custom_zombie_basic_scripts_zombie_brain')
    expect(text).toContain('registerSpawnables(SNAPSHOTS, COMPONENTS)')
    expect(text).toContain('export class SpawnableRegistry {')
    expect(text.endsWith('}\n')).toBe(true)
  })

  // Decision D2: a priority-0 script's start() runs before a priority -100 one's,
  // so nothing may depend on the registry's start(). Publishing at module scope
  // makes the ordering irrelevant by construction.
  it('registers at module scope, not from start()', () => {
    const text = render([zombie()]).text
    const register = text.indexOf('registerSpawnables(SNAPSHOTS,')
    const registry = text.indexOf('export class SpawnableRegistry')
    expect(register).toBeGreaterThan(-1)
    expect(register).toBeLessThan(registry)
    expect(text).toContain('  start(): void {}')
  })

  it('exports exactly one function-valued binding', () => {
    const shape = exportShape(render([zombie()]).text.replace("from '@dcl/sdk/ecs'", "from './ecs'"))
    expect(shape.error).toBeUndefined()
    expect(shape.functions).toEqual(['SpawnableRegistry'])
  })

  it('strips core-schema::Name from the snapshot literal', () => {
    expect(render([zombie()]).text).not.toContain('core-schema::Name')
  })

  it('escapes the layout string it embeds', () => {
    const source = zombie()
    const rows = source.composite.components[2].data['0'].json as { value: Array<{ layout: string }> }
    rows.value[0].layout = '{"params":{"label":{"type":"string","value":"it\'s \\\\ fine"}}}'
    const text = render([source]).text
    expect(text).toContain("layout: '{\"params\":{\"label\":{\"type\":\"string\",\"value\":\"it\\'s \\\\\\\\ fine\"}}}'")
  })

  it('stays a valid module with nothing spawnable in the project', () => {
    const { text, problems, blocking } = render([])
    expect(problems).toEqual([])
    expect(blocking).toBe(false)
    expect(text).toContain('export const Spawnables = {} as const')
    expect(text).toContain('const SNAPSHOTS: PrefabSnapshot[] = []')
    expect(text).not.toContain('import * as script_')
  })

  it('ignores prefabs that are not spawnable and orders the rest by folder', () => {
    const arena: SpawnableSource = {
      folder: 'custom/arena_graveyard',
      data: prefab({ id: 'arena-uuid', name: 'Arena Graveyard', spawnable: { max: 1 } }),
      composite: { version: 1, components: [{ name: 'core::Transform', data: { '0': { json: { parent: 0 } } } }] }
    }
    const plain: SpawnableSource = {
      folder: 'custom/bench',
      data: prefab({ id: 'bench-uuid', name: 'Bench' }),
      composite: { version: 1, components: [] }
    }
    const text = render([zombie(), plain, arena]).text
    expect(text).not.toContain('bench-uuid')
    expect(text.indexOf('ArenaGraveyard')).toBeLessThan(text.indexOf('ZombieBasic'))
  })
})

describe('the generation-time lint', () => {
  it('blocks a script with more than one function-valued export', () => {
    const { problems, blocking } = render([zombie()], {
      [BRAIN]: `${BRAIN_SOURCE}\nexport function helper(): void {}`
    })
    expect(blocking).toBe(true)
    expect(problems.join('\n')).toContain('must export exactly one class')
    expect(problems.join('\n')).toContain('ZombieBrain, helper')
  })

  it('blocks a script with no class at all', () => {
    const { problems, blocking } = render([zombie()], { [BRAIN]: 'export const speed = 2' })
    expect(blocking).toBe(true)
    expect(problems.join('\n')).toContain('found none')
  })

  it('blocks a script it cannot parse', () => {
    expect(render([zombie()], { [BRAIN]: 'export class {{{' }).blocking).toBe(true)
  })

  it('warns, without blocking, about a re-export', () => {
    const { problems, blocking } = render([zombie()], {
      [BRAIN]: `${BRAIN_SOURCE}\nexport { other } from './other'`
    })
    expect(blocking).toBe(false)
    expect(problems.join('\n')).toContain('re-exports another module')
  })

  it('does not count type-only exports as classes', () => {
    const { problems, blocking } = render([zombie()], {
      [BRAIN]: `${BRAIN_SOURCE}\nexport type Speed = number\nexport interface Brain { hp: number }`
    })
    expect(problems).toEqual([])
    expect(blocking).toBe(false)
  })

  // The clone runner synthesises an action param as a callback into the placed
  // entity's Actions component — a clone has no such entity, so the call goes
  // nowhere. Worth saying out loud; not worth refusing to regenerate over.
  it('warns about an action param', () => {
    const source = zombie()
    const rows = source.composite.components[2].data['0'].json as { value: Array<{ layout: string }> }
    rows.value[0].layout = '{"params":{"onHit":{"type":"action","value":{"entity":0,"action":""}}},"actions":[]}'
    const { problems, blocking } = render([source])
    expect(blocking).toBe(false)
    expect(problems.join('\n')).toContain('`onHit` is an action')
  })

  // Nobody opened the per-player pool while `instancing` lived only in data.json:
  // the placed anchor's own guarded self-open was the whole mechanism, so a rig
  // with no anchor never spawned. The registry knows the roster is scene-wide.
  it('opens the per-player pool for a perPlayer prefab, guarded', () => {
    const { text, problems, blocking } = render([zombie(), rig()])
    expect(problems).toEqual([])
    expect(blocking).toBe(false)
    expect(text).toContain("import { perPlayer, poolFor, registerSpawnables, type PrefabSnapshot } from './runtime/spawner'")
    expect(text).toContain("    instancing: 'perPlayer',")
    expect(text).toContain('    if (poolFor(Spawnables.PlayerRig) === null) perPlayer(Spawnables.PlayerRig)')
    // the other prefab is on demand and gets no call
    expect(text).not.toContain('perPlayer(Spawnables.ZombieBasic)')
    expect(exportShape(text.replace("from '@dcl/sdk/ecs'", "from './ecs'")).functions).toEqual([
      'SpawnableRegistry'
    ])
  })

  it('leaves start() empty and the import narrow when nothing is per player', () => {
    const text = render([zombie()]).text
    expect(text).toContain("    instancing: 'onDemand',")
    expect(text).toContain("import { registerSpawnables, type PrefabSnapshot } from './runtime/spawner'")
    expect(text).not.toContain('perPlayer(')
  })

  it('dedupes a duplicate alias and says which folders collided', () => {
    const other = zombie()
    other.folder = 'custom/zombie_basic_2'
    other.data = prefab({ id: 'other-uuid', name: 'Zombie  Basic', spawnable: { max: 4 } })
    const { text, problems, blocking } = render([zombie(), other])
    expect(blocking).toBe(false)
    expect(problems.join('\n')).toContain('both read as `ZombieBasic`')
    expect(text).toContain("  ZombieBasic: 'zombie-uuid' as PrefabRef")
    expect(text).toContain("  ZombieBasic2: 'other-uuid' as PrefabRef")
  })

  it('flags a PrefabRef param aimed at a prefab that is not spawnable', () => {
    const director: SpawnableSource = {
      folder: 'custom/wave_director',
      data: prefab({ id: 'director-uuid', name: 'Wave Director', spawnable: { max: 1 } }),
      composite: {
        version: 1,
        components: [
          {
            name: 'asset-packs::Script',
            data: {
              '0': {
                json: {
                  value: [
                    {
                      path: '{assetPath}/scripts/wave-director.ts',
                      priority: 0,
                      layout: '{"params":{"zombie":{"type":"string","value":"bench-uuid"}},"actions":[]}'
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
    const plain: SpawnableSource = {
      folder: 'custom/bench',
      data: prefab({ id: 'bench-uuid', name: 'Bench' }),
      composite: { version: 1, components: [] }
    }
    const source = [
      "import { type Entity } from '@dcl/sdk/ecs'",
      "import { type PrefabRef } from './spawnables'",
      'export class WaveDirector {',
      '  constructor(public src: string, public entity: Entity, public zombie: PrefabRef) {}',
      '}'
    ].join('\n')
    const { problems, blocking } = render([director, plain], {
      'custom/wave_director/scripts/wave-director.ts': source
    })
    expect(blocking).toBe(false)
    expect(problems.join('\n')).toContain('points at Bench, which is not Spawnable')
  })

  it('says so when a referenced prefab is not in the project at all', () => {
    const director: SpawnableSource = {
      folder: 'custom/wave_director',
      data: prefab({ id: 'director-uuid', name: 'Wave Director', spawnable: { max: 1 } }),
      composite: {
        version: 1,
        components: [
          {
            name: 'asset-packs::Script',
            data: {
              '0': {
                json: {
                  value: [
                    {
                      path: '{assetPath}/scripts/wave-director.ts',
                      priority: 0,
                      layout: '{"params":{"zombie":{"type":"string","value":"gone-uuid"}},"actions":[]}'
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
    const source = [
      "import { type Entity } from '@dcl/sdk/ecs'",
      'export class WaveDirector {',
      '  constructor(public src: string, public entity: Entity, public zombie: PrefabRef) {}',
      '}'
    ].join('\n')
    const { problems } = render([director], {
      'custom/wave_director/scripts/wave-director.ts': source
    })
    expect(problems.join('\n')).toContain('not in this project')
  })

  it('reports an unreadable script without blocking the regeneration', () => {
    const { problems, blocking } = render([zombie()], {})
    expect(blocking).toBe(false)
    expect(problems.join('\n')).toContain('could not be read')
  })
})

describe('PrefabRef param detection', () => {
  it('finds both the single and the list annotation', () => {
    const text = 'constructor(public zombie: PrefabRef, public arenas: PrefabRef[], public n: number) {}'
    expect(prefabRefParams(text)).toEqual(['zombie', 'arenas'])
  })

  it('ignores ordinary string params', () => {
    expect(prefabRefParams('public board: string')).toEqual([])
  })
})

// The bug this table exists for: @dcl/sdk/ecs defines every component behind a
// /* @__PURE__ */ call, so a scene that never imports Billboard does not have it,
// and a clone built from a snapshot that names it loses it in silence. The live
// probe logged exactly that — "[spawner] unknown component 'core::Billboard'".
describe('the component table the registry hands the runtime', () => {
  const billboardZombie = (): SpawnableSource => {
    const source = zombie()
    source.composite.components.push(
      { name: 'core::Billboard', data: { '0': { json: { billboardMode: 1 } } } },
      { name: 'core::Animator', data: { '0': { json: { states: [] } } } },
      { name: 'asset-packs::Counter', data: { '0': { json: { value: 3 } } } }
    )
    return source
  }

  /** the component names the emitted COMPONENTS table maps, in emission order */
  const table = (text: string): string[] => {
    const block = /const COMPONENTS: Record<string, unknown> = \{([\s\S]*?)\n\}/.exec(text)
    return [...(block?.[1] ?? '').matchAll(/'([^']+)':/g)].map((m) => m[1])
  }

  it('imports every SDK component its snapshots name, and maps it by composite name', () => {
    const text = render([billboardZombie()]).text
    expect(text).toContain("import { type Entity, Animator, Billboard, Transform } from '@dcl/sdk/ecs'")
    expect(text).toContain("  'core::Animator': Animator")
    expect(text).toContain("  'core::Billboard': Billboard")
    expect(text).toContain("  'core::Transform': Transform")
    expect(text).toContain('registerSpawnables(SNAPSHOTS, COMPONENTS)')
  })

  it('leaves a custom component to the engine — it is defined by its composite, not importable', () => {
    const text = render([billboardZombie()]).text
    // the snapshot still names it, so a clone still gets it: what it must not do
    // is import something no module exports
    expect(text).toContain("{ name: 'asset-packs::Counter'")
    expect(table(text)).toEqual(['core::Animator', 'core::Billboard', 'core::Transform'])
  })

  it('names no component when nothing spawnable is in the project', () => {
    const text = render([]).text
    expect(text).toContain("import { type Entity } from '@dcl/sdk/ecs'")
    expect(text).toContain('registerSpawnables(SNAPSHOTS)')
    expect(text).not.toContain('COMPONENTS')
  })

  // The emitted import is code a creator ships: a name @dcl/sdk/ecs does not
  // export breaks their build in a generated file. Every component the editor can
  // author is checked against the SDK's own declarations — the installed pin,
  // not a list in someone's head. (Read as text: under Vite a namespace import
  // resolves `Animator` to the generated factory, while the scene's esbuild build
  // resolves it to the bound component, and only the declarations say what the
  // package promises either way.)
  it('never names an export @dcl/sdk/ecs does not have', () => {
    const declared = sdkComponentDeclarations()
    for (const name of ALLOWED_COMPONENTS) {
      if (name.includes('::')) continue
      expect(declared.has(name), `@dcl/sdk/ecs does not export ${name}`).toBe(true)
    }
  })

  it('is a contract with the runtime module the registry imports', () => {
    // the carried copies are byte-identity synced with the master this asserts against
    const spawner = readPrefabFile('player-rig/scripts/runtime/spawner.ts')
    expect(spawner).toContain(SPAWNER_COMPONENTS_CONTRACT)
    expect(spawner).toContain('hub().components?.get(name)')
  })
})

describe('the Game Config side-effect import', () => {
  it('is emitted when the accessor is on disk — nothing else imports it', () => {
    const { text } = renderSpawnables({
      prefabs: [zombie()],
      scripts: { [BRAIN]: BRAIN_SOURCE },
      gameConfig: true
    })
    expect(text).toContain("import './game-config'")
    // and it must sit above the module that reads it at construction time
    expect(text.indexOf("import './game-config'")).toBeLessThan(text.indexOf('registerSpawnables('))
  })

  it('is left out when the project has no Game Config, so the import cannot dangle', () => {
    expect(render([zombie()]).text).not.toContain("import './game-config'")
  })
})
