// Installing operations carry modules. Dropping a prefab and turning Spawnable
// on both copy the `runtime/` modules the scripts import into the scene, because
// nothing in a creator's project resolves back to this repo. One copy per
// project, under `src/scripts/runtime/`: a placed prefab's script reaches it by
// climbing out of its folder, and the generated registry sits beside it.
//
// This is the renderer-side twin of `scripts/sync-runtime-modules.mjs`. The
// duplication is deliberate: that one walks the repo over `fs` at build time,
// this one walks a creator's project over the data layer at authoring time, and
// giving them one home would drag node's `fs` into the browser bundle. They agree
// on the one thing that matters — which specifiers count as runtime imports.
import { GAME_IMPORT } from '../script/template'

const RUNTIME_DIR = 'runtime'

// First line of every runtime-module master. A pass only ever overwrites a file
// carrying it, so a creator's own file — even one named like a master, sitting
// in a runtime/ folder — is provably never touched.
export const RUNTIME_MODULE_MARKER = 'Generated by Decentraland Studio.'

// The ownership proof, as one predicate every vendoring pass shares. It lives
// here rather than inline because the guarantee above is only true while ALL of
// them apply it — the pass that forgot is how a creator's file gets replaced by
// a master of the same name, with no prompt and no undo.
export function isVendoredCopy(text: string): boolean {
  return text.includes(RUNTIME_MODULE_MARKER)
}

// Drop comments so an example import inside a doc header — prefab scripts
// document their own usage that way — is never mistaken for a real dependency.
// String literals survive, since specifiers live in them.
export function stripComments(text: string): string {
  let out = ''
  let i = 0
  while (i < text.length) {
    const c = text[i]
    const next = text[i + 1]
    if (c === '/' && next === '/') {
      while (i < text.length && text[i] !== '\n') i++
      continue
    }
    if (c === '/' && next === '*') {
      i += 2
      while (i < text.length && !(text[i] === '*' && text[i + 1] === '/')) i++
      i += 2
      continue
    }
    if (c === '`' || c === "'" || c === '"') {
      out += c
      i++
      while (i < text.length && text[i] !== c) {
        if (text[i] === '\\') {
          out += text[i]
          i++
        }
        out += text[i] ?? ''
        i++
      }
      out += c
      i++
      continue
    }
    out += c
    i++
  }
  return out
}

// A fresh regex per call: `lastIndex` is per-object state, and one shared /g
// literal between matchAll and replace is a classic silent-skip bug.
function specifierPattern(): RegExp {
  return /\b(from|import)\s*(['"])([^'"\n]+)\2/g
}

// Every static module specifier in `text`. Dynamic import() is banned repo-wide
// and deliberately unmatched — a runtime module reached that way would not be
// carried, and would 404 inside the creator's scene rather than here.
export function importSpecifiers(text: string): string[] {
  const specs: string[] = []
  for (const m of stripComments(text).matchAll(specifierPattern())) specs.push(m[3])
  return specs
}

function normalize(path: string): string {
  const out: string[] = []
  for (const seg of path.split('/')) {
    if (seg === '' || seg === '.') continue
    if (seg === '..') {
      if (out.length === 0 || out[out.length - 1] === '..') out.push('..')
      else out.pop()
      continue
    }
    out.push(seg)
  }
  return out.join('/')
}

function withTs(rel: string): string {
  return /\.tsx?$/.test(rel) ? rel : `${rel}.ts`
}

// The part of a `runtime/…` specifier that names the module inside runtime/, or
// null when the specifier is not a runtime import. `./runtime/pure/rng` and a
// nested script's `../runtime/pure/rng` both yield `pure/rng.ts`.
//
// Two shapes reach the one shared copy under src/scripts/runtime/: a script
// beside it says `./runtime/x`, and a placed prefab's script climbs out of
// custom/<folder>/scripts/ with `../../../src/scripts/runtime/x`. Anything else
// — a reach into another prefab folder — is not a runtime import.
const RUNTIME_PREFIX = new RegExp(`^(\\.\\.?/)+$|^(\\.\\./)+src/scripts/$`)

export function runtimeModuleOf(spec: string): string | null {
  if (!spec.startsWith('.')) return null
  const i = spec.lastIndexOf(`${RUNTIME_DIR}/`)
  if (i < 0) return null
  if (!RUNTIME_PREFIX.test(spec.slice(0, i))) return null
  const inner = normalize(spec.slice(i + RUNTIME_DIR.length + 1))
  return inner === '' ? null : withTs(inner)
}

/** The runtime modules a script imports directly, as paths inside `runtime/`. */
export function runtimeImportsOf(text: string): string[] {
  const found: string[] = []
  for (const spec of importSpecifiers(text)) {
    const rel = runtimeModuleOf(spec)
    if (rel !== null && !found.includes(rel)) found.push(rel)
  }
  return found
}

// The one module a project carries before anything in it asks: on a scene with a
// Multiplayer Server the game module is vendored unasked (prefabs/generate.ts), so
// `game.` completes and hovers before a creator has typed the import. Read off the
// specifier a script writes, so the two can never name different files.
export const GAME_MODULE_REL = runtimeImportsOf(`import { game } from '${GAME_IMPORT}'`)[0]

// A master's own imports are plain relative paths to its siblings (`./rpc`,
// `./pure/rng`), never `./runtime/…` — resolving them is how a walk that starts
// at one master reaches the whole closure.
export function resolveSibling(fromRel: string, spec: string): string | null {
  if (!spec.startsWith('.')) return null
  const dir = fromRel.includes('/') ? fromRel.slice(0, fromRel.lastIndexOf('/')) : ''
  const joined = normalize(dir === '' ? spec : `${dir}/${spec}`)
  if (joined === '' || joined.startsWith('..')) return null
  return withTs(joined)
}

// Every module an entry script pulls in, transitively, as paths inside runtime/.
// `read(rel)` returns a master's text or null; a missing master throws, because
// carrying an incomplete set produces a scene that fails to build with an error
// pointing at generated code the creator never wrote.
export function transitiveModules(entryText: string, read: (rel: string) => string | null): string[] {
  const seen = new Set<string>()
  const queue = runtimeImportsOf(entryText)
  while (queue.length > 0) {
    const rel = queue.shift() as string
    if (seen.has(rel)) continue
    const text = read(rel)
    if (text === null) throw new Error(`no master for runtime module '${rel}'`)
    seen.add(rel)
    for (const spec of importSpecifiers(text)) {
      const dep = resolveSibling(rel, spec)
      if (dep !== null && !seen.has(dep)) queue.push(dep)
    }
  }
  return [...seen].sort()
}

// Relative imports that break when a script is copied into a prefab folder.
// Only `runtime/` modules travel — every one of them names the project's single
// shared copy, from either side, so runtimeModuleOf returning non-null is the
// exemption. Everything else, `./game-config` or a reach into another prefab
// folder, resolves somewhere that does not exist once the copy sits in the
// folder — a build failure in a file the creator never wrote. A specifier that
// walks up to the same project path from both directories still resolves and is
// not reported.
export function strandedImports(text: string, fromDir: string, toDir: string): string[] {
  const from = normalize(fromDir)
  const to = normalize(toDir)
  const stranded: string[] = []
  for (const spec of importSpecifiers(text)) {
    if (!spec.startsWith('.') || runtimeModuleOf(spec) !== null) continue
    if (normalize(`${from}/${spec}`) === normalize(`${to}/${spec}`)) continue
    if (!stranded.includes(spec)) stranded.push(spec)
  }
  return stranded
}
