// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
import {
  InputAction,
  PlayerIdentityData,
  Schemas,
  Transform,
  TriggerArea,
  engine,
  pointerEventsSystem,
  type Entity,
  type LastWriteWinElementSetComponentDefinition
} from '@dcl/sdk/ecs'
import { isServer, registerMessages, syncEntity } from '@dcl/sdk/network'
import { AUTH_SERVER_PEER_ID } from '@dcl/sdk/network/message-bus-sync'
import { Storage } from '@dcl/sdk/server'
import { createRpc, type Rpc } from './rpc'
import { markServerReady, serverLifeState, startServerLife, type ServerLifeState } from './serverLife'
import { previewLog, protectSynced } from './protectedSync'
import { serverState, type ServerState } from './serverState'
import { FlushDebouncer } from './playerStore'
import { playerPosition, sceneLocalPosition } from './playerPositions'
import { interval, PhaseWatcher } from './schedule'
import { pool, snapshotRootComponent, type Pool } from './spawner'
import { getServerTime, initTimeSync } from './timeSync'
import { onZone } from './zoneBus'
import { createRng, type Rng } from './pure/rng'
import { zoneKey } from './pure/zoneRegistry'
import {
  GameCore,
  layoutSeed,
  setTrace,
  type CorePorts,
  type Player,
  type RoundInfo,
  type Vec3,
  type ZoneVolume
} from './pure/gameCore'

// The creator's one object. Every scene runs one shared copy — the game — plus
// a copy per player's screen; `game` is how a script talks to the shared one.
// This file is transport and timing only; every rule (direction, one handler
// per name, FIFO, rate limits, the green guard, boot order) lives in
// pure/gameCore.ts, where the harness can reach it.
//
//   game.onMessage('openChest', (data, player) => { ... })   // in the game, for everyone
//   onClick(this.entity, () => void game.send('openChest', { chest: this.entity }))
//
// Timing, solved here once. Schemas must register at module scope (the engine
// seals after load), so ONE rpc namespace carries every ask and ONE broadcast
// envelope carries every tell — creator names are payload, never schema, which
// is why onMessage is legal anywhere: module scope, start(), mid-round. And
// isServer() answers false for every module body, so which transport half
// installs is decided on the first engine tick (the outcomes idiom).
//
// Cross-copy: every prefab carries its own copy of this file, so the whole
// driver — core, rpc, tell room, fact entities — lives on
// globalThis.__dclGame_v1 and is probed by shape. Only the first copy registers
// the schemas; sibling copies adopt its transport objects, which is what keeps
// registration exactly-once.

const GAME_KEY = '__dclGame_v1'
const TELL = 'game.tell'
// A revision off the wire is data: a forged huge one would freeze its key for
// the session, since the mirror drops anything at or below what it has seen.
const MAX_REV = 2 ** 30
const clampRev = (rev: number): number => {
  const n = Number(rev)
  return Number.isFinite(n) && n > 0 ? Math.min(Math.floor(n), MAX_REV) : 0
}
const PARTICIPANT = 'game'
// Storage namespaces — creators' durable data lives under these forever.
const SAVED_STORE_KEY = 'game.saved'
const PLAYER_STORE_KEY = 'game'
// serverState stash for the coming round's seed (§11 seed secrecy).
const ROUND_STORE_KEY = 'game.round'
const TRANSFORM_NAME = 'core::Transform'
// The internal zone-claim ask: a screen detects a crossing locally (only it
// has avatar colliders), the game re-verifies before anything counts.
const ZONE_ASK = 'game.zone'
const ZONE_SWEEP_S = 0.25
const SPHERE_MESH = 1
// The Play HUD's Game strip reads this line. serverLife owns the ladder, and
// the editor has no view into the played scene's ECS, so the console is the
// only channel that reaches it — a ladder re-implemented editor-side would be a
// second truth. Client-only: a screen is the one copy that can observe whether
// the game is reachable at all.
const LIFE_LINE = '[studio] game-life'

export type { Player }

// Each top-level game.state key rides its own synced entity, so a single write
// stays far from the transport's 12 KB chunk edge and unrelated keys move
// independently. A sibling copy may have defined the component first.
function defineSharedFact() {
  return engine.defineComponent('runtime::SharedFact', {
    key: Schemas.String,
    json: Schemas.String,
    rev: Schemas.Int
  })
}
const SharedFact =
  (engine.getComponentOrNull('runtime::SharedFact') as ReturnType<typeof defineSharedFact> | null) ?? defineSharedFact()

function registerTell() {
  return registerMessages({
    [TELL]: Schemas.Map({ name: Schemas.String, body: Schemas.String, to: Schemas.String })
  })
}
type TellRoom = ReturnType<typeof registerTell>

interface HeldAsk {
  name: string
  json: string
  resolve: (json: string) => void
  reject: (error: Error) => void
}

type LayoutPlan = (rng: Rng, round: RoundInfo) => Vec3[]

interface LayoutSpec {
  planFn: LayoutPlan
  pool: Pool | null
  watcher: PhaseWatcher
  warned: boolean
}

interface GameDriver {
  core: GameCore
  rpc: Rpc
  tell: TellRoom
  role: 'server' | 'client' | null
  ticking: boolean
  /** every name a handler registered under, so a late server fork can arm them all */
  names: Set<string>
  /** blue asks held while the ladder says waking */
  held: HeldAsk[]
  /** server: fact key → its synced entity */
  factEntities: Map<string, Entity>
  /** server: stale snapshot entities awaiting next-tick removal */
  retirals: Entity[]
  /** client: last rev seen per key, to notice a retired fact's entity vanish */
  seenRevs: Map<string, number>
  saved: ServerState<Record<string, unknown>> | null
  /** server: the next round's seed, stashed server-private until published */
  roundSeed: ServerState<{ nextSeed: number }> | null
  dirtyPlayers: Map<Player, Record<string, unknown>>
  flush: FlushDebouncer
  /** client: zone keys already subscribed on the zone bus */
  watchedZones: Set<string>
  /** server: dt accumulator for the 4 Hz zone sweep */
  sweepAccum: number
  /** client: prefab → its seeded-layout plan, rebuilt per round */
  layouts: Map<string, LayoutSpec>
  /** client: the last ladder state announced to the editor, so only changes print */
  lifeSaid: ServerLifeState | null
}

// Byte-identical copies of this file are still separate module instances, so
// the shared driver is probed by shape — instanceof would reject a sibling's.
function isDriver(value: unknown): value is GameDriver {
  return (
    typeof value === 'object' &&
    value !== null &&
    'core' in value &&
    typeof value.core === 'object' &&
    value.core !== null &&
    'handleAsk' in value.core &&
    typeof (value.core as { handleAsk: unknown }).handleAsk === 'function' &&
    'names' in value &&
    value.names instanceof Set &&
    'held' in value &&
    Array.isArray(value.held)
  )
}

function driver(): GameDriver {
  const globals = globalThis as unknown as Record<string, unknown>
  const current = globals[GAME_KEY]
  if (isDriver(current)) return current
  const created = createDriver()
  globals[GAME_KEY] = created
  return created
}

function createDriver(): GameDriver {
  const d: GameDriver = {
    core: new GameCore(makePorts(() => d)),
    rpc: createRpc('game'),
    tell: registerTell(),
    role: null,
    ticking: false,
    names: new Set<string>(),
    held: [],
    factEntities: new Map<string, Entity>(),
    retirals: [],
    seenRevs: new Map<string, number>(),
    saved: null,
    roundSeed: null,
    dirtyPlayers: new Map<Player, Record<string, unknown>>(),
    flush: new FlushDebouncer(),
    watchedZones: new Set<string>(),
    sweepAccum: 0,
    layouts: new Map<string, LayoutSpec>(),
    lifeSaid: null
  }
  return d
}

// rpc's retry budget (~12 s) is shorter than a production cold start (~15 s):
// while the ladder says waking, hold the ask — the client tick drains the
// queue once the first heartbeat lands, so a cold start is a spinner, never a
// mystery timeout.
function sendAsk(d: GameDriver, name: string, json: string): Promise<string> {
  if (serverLifeState() === 'waking') {
    return new Promise<string>((resolve, reject) => {
      d.held.push({ name, json, resolve, reject })
    })
  }
  return d.rpc.call<string>(name, json)
}

function makePorts(self: () => GameDriver): CorePorts {
  return {
    now: () => Date.now(),
    sendAsk: (name, json) => sendAsk(self(), name, json),
    sendTell: (name, json, to) => {
      try {
        // {to} is enforced by the transport (the SFU never delivers it to
        // anyone else); the receive-side check is only defence in depth
        const target = to === undefined ? undefined : to.toLowerCase()
        self().tell.send(
          TELL,
          { name, body: json, to: target ?? '' },
          target === undefined ? undefined : { to: [target] }
        )
      } catch {
        // transport down — a tell is a moment, it fades
      }
    },
    publishFact: (key, json, rev) => {
      const d = self()
      const existing = d.factEntities.get(key)
      if (existing !== undefined) {
        // the entity can be gone underneath us (the SDK does not yet validate
        // an inbound delete), so re-create rather than throwing on every write
        const fact = SharedFact.getMutableOrNull(existing)
        if (fact !== null) {
          fact.json = json
          fact.rev = rev
          return
        }
        d.factEntities.delete(key)
      }
      const entity = engine.addEntity()
      SharedFact.create(entity, { key, json, rev })
      // auto sync id + refuse-all validator, fused: never synced-but-unguarded
      syncEntity(entity, [SharedFact.componentId])
      protectSynced(entity, [SharedFact], () => false)
      d.factEntities.set(key, entity)
    },
    retireFact: (key) => {
      const d = self()
      const entity = d.factEntities.get(key)
      if (entity === undefined) return
      d.factEntities.delete(key)
      // removeEntity waits a tick — never in the frame that republishes (the
      // NetworkEntity survives until the CRDT flush)
      d.retirals.push(entity)
    },
    emitError: (card) => {
      console.error(`[${card.side}] ${card.name}: ${card.message}`)
    },
    devWarn: (message) => {
      console.log(`[game] ${message}`)
    },
    loadSaved: async () => {
      const store = savedStore(self())
      await store.restore()
      return { ...store.get() }
    },
    storeSaved: (key, value) => {
      const d = self()
      savedStore(d).patch({ [key]: value })
      d.flush.mark(Date.now())
    },
    loadPlayerData: async (player) => {
      const raw = await Storage.player.get<unknown>(player, PLAYER_STORE_KEY)
      return typeof raw === 'object' && raw !== null ? { ...(raw as Record<string, unknown>) } : {}
    },
    storePlayerData: (player, data) => {
      const d = self()
      d.dirtyPlayers.set(player, data)
      d.flush.mark(Date.now())
    },
    // Leave checkpoint: the debounce window would outlive the visit, so the
    // record goes out now. Same retry semantics as flushDurable.
    flushPlayerData: (player) => {
      const d = self()
      const data = d.dirtyPlayers.get(player)
      if (data === undefined) return
      void Storage.player.set(player, PLAYER_STORE_KEY, data).then((ok) => {
        if (!ok) {
          d.flush.mark(Date.now())
          return
        }
        if (d.dirtyPlayers.get(player) === data) d.dirtyPlayers.delete(player)
      })
    },
    findZones: (key) => findZoneVolumes(key),
    playerPosition: (player) => playerPosition(player),
    // The coming round's seed lives in serverState — reading it from a client
    // throws — and only leaves the stash by being published in the tuple, so
    // no client can precompute the next layout (§11 seed secrecy).
    takeNextSeed: () => {
      const store = roundSeedStore(self())
      const seed = store.get().nextSeed
      store.patch({ nextSeed: freshSeed() })
      return seed
    }
  }
}

function savedStore(d: GameDriver): ServerState<Record<string, unknown>> {
  if (d.saved === null) {
    d.saved = serverState<Record<string, unknown>>({ key: SAVED_STORE_KEY, defaults: () => ({}), persist: true })
  }
  return d.saved
}

function freshSeed(): number {
  return Math.floor(Math.random() * 0x7fffffff)
}

function roundSeedStore(d: GameDriver): ServerState<{ nextSeed: number }> {
  if (d.roundSeed === null) {
    d.roundSeed = serverState<{ nextSeed: number }>({ key: ROUND_STORE_KEY, defaults: () => ({ nextSeed: freshSeed() }) })
  }
  return d.roundSeed
}

// Write-behind checkpoint: saved and playerData land after the debounce window,
// never per tick — storage writes are capped. A failed write stays dirty and
// re-arms the window.
async function flushDurable(d: GameDriver): Promise<void> {
  if (d.saved !== null) await d.saved.flush()
  for (const [player, data] of [...d.dirtyPlayers]) {
    const ok = await Storage.player.set(player, PLAYER_STORE_KEY, data)
    if (!ok) {
      d.flush.mark(Date.now())
      continue
    }
    if (d.dirtyPlayers.get(player) === data) d.dirtyPlayers.delete(player)
  }
}

// Every ask rides the one rpc namespace; the method map is per-name, so a
// handler can arm at any time. The player's durable record is restored before
// their first green handler, so playerData(p).get() never races the load.
function armAsk(d: GameDriver, name: string): void {
  d.rpc.handle(name, (body, from) => {
    const player = from.toLowerCase()
    const json = typeof body === 'string' ? body : JSON.stringify(body ?? null)
    return d.core.restorePlayerData(player).then(() => d.core.handleAsk(name, json, player))
  })
}

function myAddress(): string {
  return PlayerIdentityData.getOrNull(engine.PlayerEntity)?.address.toLowerCase() ?? ''
}

type NameValue = { value: string }
type NameComponent = LastWriteWinElementSetComponentDefinition<NameValue>

// A sibling copy of a runtime module may already have defined it.
function nameComponent(): NameComponent {
  const existing = engine.getComponentOrNull('core-schema::Name')
  if (existing !== null) return existing as NameComponent
  return engine.defineComponent('core-schema::Name', { value: Schemas.String })
}

// Zones are resolved by NAME, matched the way zoneBus matches on the client
// (trimmed, case-insensitive) — the name is the only id a zone has. Several
// areas may share a name; being inside any of them is being inside the zone.
function findZoneVolumes(key: string): ZoneVolume[] {
  const found: ZoneVolume[] = []
  if (key === '') return found
  const names = nameComponent()
  for (const [entity, name] of engine.getEntitiesWith(names, TriggerArea)) {
    if (zoneKey(name.value) !== key) continue
    const transform = Transform.getOrNull(entity)
    // Rotation and scale are the zone's own; the editor places zones at the
    // scene root, and only the center needs the parent chain composed.
    const center = sceneLocalPosition(entity)
    if (transform === null || center === null) continue
    found.push({
      shape: TriggerArea.getOrNull(entity)?.mesh === SPHERE_MESH ? 'sphere' : 'box',
      center,
      rotation: transform.rotation,
      scale: transform.scale
    })
  }
  return found
}

// Headless presence: SDK onEnterScene/getPlayer never fire on the server, but
// synced PlayerIdentityData entities do arrive — the identity set IS the
// roster. The server's own PlayerEntity is not a player.
function presentAddresses(): Player[] {
  const seen = new Set<Player>()
  for (const [entity, identity] of engine.getEntitiesWith(PlayerIdentityData)) {
    if (entity === engine.PlayerEntity) continue
    const address = (identity.address ?? '').toLowerCase()
    if (address !== '') seen.add(address)
  }
  return [...seen]
}

function armZoneClaims(d: GameDriver): void {
  d.rpc.handle(ZONE_ASK, (body, from) => {
    const raw = typeof body === 'string' ? body : ''
    let claim: Record<string, unknown> = {}
    try {
      const parsed: unknown = JSON.parse(raw)
      if (typeof parsed === 'object' && parsed !== null) claim = parsed as Record<string, unknown>
    } catch {
      // an empty claim fails the name check below
    }
    const zone = typeof claim.zone === 'string' ? claim.zone : ''
    const kind = claim.kind === 'exit' ? 'exit' : 'enter'
    return d.core.zoneClaim(zone, kind, from.toLowerCase())
  })
}

function watchZone(d: GameDriver, zone: string): void {
  const key = zoneKey(zone)
  if (key === '' || d.watchedZones.has(key)) return
  d.watchedZones.add(key)
  onZone(zone, 'any', (event) => {
    if (!event.local) return
    void claimZone(d, zone, event.kind)
  })
}

// A refused claim is an answer (outside, unknown zone) — the green callback
// simply never fires; there is nothing to surface on the screen.
async function claimZone(d: GameDriver, zone: string, kind: 'enter' | 'exit'): Promise<void> {
  try {
    await sendAsk(d, ZONE_ASK, JSON.stringify({ zone, kind }))
  } catch {
    // refused or transport down — deliberately quiet
  }
}

function armTick(d: GameDriver): void {
  if (d.ticking) return
  d.ticking = true
  engine.addSystem(
    (dt) => {
      const live = driver()
      if (live.role === null) {
        // the platform has resolved the role by the first tick — fork now, and
        // skip the role tick this frame so boot's retirals wait a full tick
        fork(live)
        return
      }
      if (live.role === 'server') serverTick(live, dt)
      else clientTick(live)
    },
    undefined,
    'runtime-game'
  )
}

function fork(d: GameDriver): void {
  const server = isServer()
  d.role = server ? 'server' : 'client'
  d.core.setRole(server)
  initTimeSync()
  startServerLife(PARTICIPANT)
  if (server) {
    // Per-entity guards only cover entities this run created: the SDK mints a
    // fresh entity for an id it has never seen, and an unguarded component is
    // accepted by default — so without this a modified client could publish a
    // shared fact of its own. Component-global, armed once, refusing anyone
    // who is not the game itself (the serverLife precedent).
    SharedFact.validateBeforeChange(
      ({ senderAddress }) => senderAddress.toLowerCase() === AUTH_SERVER_PEER_ID
    )
    for (const name of d.names) armAsk(d, name)
    armZoneClaims(d)
    // the CRDT snapshot outlives the isolate: adopt what survived, then boot
    // retires it (state resets when the game sleeps) and republishes fresh
    const adopted: Array<{ key: string; json: string; rev: number }> = []
    for (const [entity] of engine.getEntitiesWith(SharedFact)) {
      const fact = SharedFact.get(entity)
      adopted.push({ key: fact.key, json: fact.json, rev: clampRev(fact.rev) })
      d.factEntities.set(fact.key, entity)
    }
    void d.core
      .bootServer(adopted, presentAddresses())
      .catch((e: unknown) => {
        // a boot that never finishes leaves every screen's send parked forever:
        // report it, but still open the gate
        console.error(`[game] boot failed: ${e instanceof Error ? e.message : String(e)}`)
      })
      .then(() => markServerReady(PARTICIPANT))
  } else {
    d.tell.onMessage(TELL, (msg) => {
      if (msg.to !== '' && msg.to !== myAddress()) return
      d.core.handleTell(msg.name, msg.body)
    })
    for (const zone of d.core.zoneNames()) watchZone(d, zone)
  }
}

function serverTick(d: GameDriver, dt: number): void {
  for (const entity of d.retirals.splice(0)) engine.removeEntity(entity)
  d.core.flushState()
  d.core.presentPlayers(presentAddresses())
  d.sweepAccum += dt
  if (d.sweepAccum >= ZONE_SWEEP_S) {
    d.sweepAccum = 0
    d.core.sweepZones(Date.now())
  }
  if (d.flush.isDue(Date.now())) {
    d.flush.clear()
    void flushDurable(d)
  }
}

function clientTick(d: GameDriver): void {
  const present = new Set<string>()
  for (const [entity] of engine.getEntitiesWith(SharedFact)) {
    const fact = SharedFact.get(entity)
    const rev = clampRev(fact.rev)
    present.add(fact.key)
    d.core.applyFact(fact.key, fact.json, rev)
    d.seenRevs.set(fact.key, rev)
  }
  for (const [key, rev] of [...d.seenRevs]) {
    if (present.has(key)) continue
    // the game retired the fact's entity (boot wipe) — the mirror follows
    d.seenRevs.delete(key)
    d.core.applyRetire(key, rev + 1)
  }
  const life = serverLifeState()
  if (life !== d.lifeSaid) {
    d.lifeSaid = life
    previewLog(`${LIFE_LINE} ${life}`)
  }
  if (d.held.length > 0 && life !== 'waking') {
    for (const ask of d.held.splice(0)) {
      d.rpc.call<string>(ask.name, ask.json).then(ask.resolve, ask.reject)
    }
  }
  layoutTick(d)
}

// Layouts are screen-built: every client reconstructs the same field from the
// round tuple (one per-prefab rng stream off the round's seed), so a late
// joiner fast-forwards by arithmetic — the PhaseWatcher's first step IS the
// current round, never a replay — and the server materialises nothing.
function layoutTick(d: GameDriver): void {
  if (d.layouts.size === 0) return
  const round = d.core.round
  if (round.number <= 0) return
  for (const [prefab, spec] of [...d.layouts]) {
    if (spec.watcher.step(round.number) === null) continue
    replanLayout(d, prefab, spec, round)
  }
}

function replanLayout(d: GameDriver, prefab: string, spec: LayoutSpec, round: RoundInfo): void {
  if (spec.pool === null) {
    try {
      spec.pool = pool(prefab, 'seeded')
    } catch (e) {
      // keep the registration: the message names the fix, and dropping it here
      // meant one bad round silently ended that layout for the whole session
      if (!spec.warned) {
        spec.warned = true
        console.error(
          `[you] game.layout: no prefab for '${prefab}'. Pass one from Spawnables — ` +
            `game.layout(Spawnables.Rock, …) — and mark it Spawnable in the Prefabs tab.`
        )
      }
      return
    }
  }
  // plan BEFORE releasing: a plan that throws must not leave the field empty
  let spots: Vec3[]
  try {
    spots = spec.planFn(createRng(layoutSeed(round.seed, prefab)), round)
  } catch (e) {
    console.error(`[you] layout('${prefab}'): ${e instanceof Error ? e.message : String(e)}`)
    return
  }
  spec.pool.releaseAll()
  // keep the authored rotation and scale, place at the planned spot
  const authored = snapshotRootComponent(prefab, TRANSFORM_NAME)
  const base = typeof authored === 'object' && authored !== null ? (authored as Record<string, unknown>) : {}
  for (let i = 0; i < spots.length; i++) {
    const at = spots[i]
    try {
      const spawned = spec.pool.acquire(i, { [TRANSFORM_NAME]: { ...base, position: { x: at.x, y: at.y, z: at.z } } })
      if (spawned === null) break // pool at max: the plan asked for more copies than the prefab allows
    } catch (e) {
      // one copy's script crashing must not cost the rest of the field
      console.error(`[you] layout('${prefab}') #${i}: ${e instanceof Error ? e.message : String(e)}`)
    }
  }
}

// One handler per name: a re-registration from the same script must replace (a
// prefab placed twice shares one handler) while a second script claiming the
// name must error. The call site is the only script identity that exists at
// runtime — best effort: a bundle that flattens filenames degrades to replace
// semantics, and the static check owns the edit-time error.
function callerScript(): string {
  for (const line of (new Error().stack ?? '').split('\n').slice(1)) {
    const match = /([^/\\ ('")]+\.[tj]sx?)/.exec(line)
    if (match !== null && match[1] !== 'game.ts' && match[1] !== 'gameCore.ts') return match[1]
  }
  return 'scene'
}

export const game = {
  /** Runs once when the game wakes up (not per player, not per round). */
  onStart(fn: () => void | Promise<void>): void {
    driver().core.onStart(fn)
  },
  /** Facts every player agrees on; a player who joins late sees them automatically. */
  get state(): Record<string, unknown> {
    return driver().core.state
  },
  /** Changes shared facts — only code inside game.onMessage (or game.onStart) can call it. */
  setState(patch: Record<string, unknown>): void {
    driver().core.setState(patch)
  },
  /** Every screen, including players who join late. */
  onStateChange(listener: (changed: Record<string, unknown>) => void): void {
    driver().core.onStateChange(listener)
  },
  /**
   * A screen's send asks the game and resolves with the handler's return.
   * The game's send is a moment: shown once, then gone. Players who join later
   * never see it — lasting facts go in game.state. `{to}` reaches one player
   * (weaker delivery — fine for a whisper).
   */
  send<T = unknown>(name: string, data?: unknown, opts?: { to?: Player }): Promise<T> {
    return driver().core.send(name, data, opts) as Promise<T>
  },
  /** In the game it hears players' asks; on a screen it hears the game. */
  onMessage<T = unknown>(name: string, fn: (data: T, player: Player) => unknown | Promise<unknown>): void {
    const d = driver()
    d.names.add(name)
    d.core.onMessage(name, fn as (data: unknown, player: Player) => unknown, callerScript())
    if (d.role === 'server') armAsk(d, name)
  },
  /** The shared clock — the same number in the game and on every screen. */
  now(): number {
    return Number(getServerTime())
  },
  /** Runs in the game when a player arrives. */
  onPlayerJoin(fn: (player: Player) => void | Promise<void>): void {
    driver().core.onPlayerJoin(fn)
  },
  /** Runs in the game when a player leaves — their player data is saved right after. */
  onPlayerLeave(fn: (player: Player) => void | Promise<void>): void {
    driver().core.onPlayerLeave(fn)
  },
  /**
   * Runs in the game when a player enters the Trigger Zone with this name —
   * the game re-checks their real position before it counts.
   */
  onEnterZone(zone: string, fn: (player: Player) => void | Promise<void>): void {
    const d = driver()
    d.core.onEnterZone(zone, fn)
    if (d.role === 'client') watchZone(d, zone)
  },
  /** Runs in the game when a verified player leaves the Trigger Zone with this name. */
  onExitZone(zone: string, fn: (player: Player) => void | Promise<void>): void {
    const d = driver()
    d.core.onExitZone(zone, fn)
    if (d.role === 'client') watchZone(d, zone)
  },
  /** Feet, about 10 times per second — for generous checks only. */
  positionOf(player: Player): Vec3 | null {
    return driver().core.positionOf(player)
  },
  /** The current round — number, seed, and when it started. number is 0 until the first round lands. */
  get round(): RoundInfo {
    return driver().core.round
  },
  /** Starts the next round for everyone — a fresh seed, every layout rebuilds. Only the game can call it. */
  newRound(): RoundInfo {
    return driver().core.newRound()
  },
  /** Runs in the game when a round starts (round 1 included) — reset state here; screens follow through game.onStateChange. */
  onRoundStart(fn: (round: RoundInfo) => void | Promise<void>): void {
    driver().core.onRoundStart(fn)
  },
  /**
   * Each player's screen builds its own copies from the round's seed — the
   * layout is identical for all, with zero messages. The callback gets
   * (rng, round) and nothing else, so it cannot diverge; it re-runs on every
   * new round.
   */
  layout(prefab: string, positions: (rng: Rng, round: RoundInfo) => Vec3[]): void {
    const d = driver()
    const existing = d.layouts.get(prefab)
    // a prefab placed twice re-registers the same plan: replace, like onMessage
    if (existing !== undefined) existing.planFn = positions
    else d.layouts.set(prefab, { planFn: positions, pool: null, watcher: new PhaseWatcher(), warned: false })
    // the plan is only "the same everywhere" on a shared clock (the spawner rule)
    initTimeSync()
  },
  /** Runs in the game every `seconds` seconds — the timer starts fresh when the game wakes up. */
  every(seconds: number, fn: () => void | Promise<void>): void {
    interval(seconds, () => {
      const d = driver()
      if (d.role !== 'server' || !d.core.booted()) return
      void d.core.runEvery(fn)
    })
  },
  /** Survives restarts and re-publishes, unlike game.state. Only the game reads or writes it. */
  saved: {
    get<T = unknown>(key: string): T | undefined {
      return driver().core.saved.get(key) as T | undefined
    },
    set(key: string, value: unknown): void {
      driver().core.saved.set(key, value)
    }
  },
  /**
   * Prints every message between the game and the screens while you play —
   * who sent it, which way it went, and how big it was. Leave it off when you
   * publish. You can also flip it mid-session from the console.
   */
  trace(on = true): void {
    setTrace(on)
  },
  /** One durable record per wallet, forever. set patches top-level keys. */
  playerData<T extends Record<string, unknown> = Record<string, unknown>>(
    player: Player
  ): { get(): Partial<T>; set(patch: Partial<T>): void } {
    return driver().core.playerData(player) as { get(): Partial<T>; set(patch: Partial<T>): void }
  }
}

/**
 * What THIS player clicks, on their screen. Decisions that count for everyone
 * go inside game.onMessage.
 */
export function onClick(entity: Entity, fn: () => void): void {
  pointerEventsSystem.onPointerDown({ entity, opts: { button: InputAction.IA_POINTER } }, fn)
}

/**
 * The entities dragged under this one, in the order they were added — the same
 * order in the game and on every screen. Use it for the group a piece owns:
 * spawn points, board faces, floors.
 */
export function childrenOf(parent: Entity): Entity[] {
  const out: Entity[] = []
  for (const [entity, transform] of engine.getEntitiesWith(Transform)) {
    if (transform.parent === parent) out.push(entity)
  }
  return out.sort((a, b) => a - b)
}

armTick(driver())
