// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// Where one copy stands relative to its spawn point.
//
// Five copies from one spawn point would otherwise occupy one metre of ground.
// The offset is a pure function of the instance id — which the server already
// replicated — so every client puts copy #7 in exactly the same place without a
// position ever crossing the wire.
//
// sqrt() on the radius draw is what spreads copies over the disc instead of
// piling them near the centre: the area of a ring grows with r, so a uniform
// draw would over-sample the middle.
import { createRng } from './rng'

const TAU = Math.PI * 2

/**
 * What a radius of 0 means depends on how many copies can exist: one copy sits
 * exactly on the spot, but several would stack in one point, which no creator
 * ever wants — so 0 with a cap above one spreads them just enough to stand
 * apart (√cap · 0.5 m: 4 copies get a metre, 16 get two). An authored radius
 * always wins.
 */
export function effectiveScatter(radius: number, atMostAtOnce: number): number {
  if (Number.isFinite(radius) && radius > 0) return radius
  if (!Number.isFinite(atMostAtOnce) || atMostAtOnce <= 1) return 0
  return Math.sqrt(atMostAtOnce) * 0.5
}

export function scatterOffset(instanceId: number, radius: number): { x: number; z: number } {
  if (!Number.isFinite(radius) || radius <= 0) return { x: 0, z: 0 }
  const rng = createRng(Math.floor(instanceId))
  const angle = rng() * TAU
  const distance = Math.sqrt(rng()) * radius
  return { x: Math.cos(angle) * distance, z: Math.sin(angle) * distance }
}
