// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// A platform's position is DERIVED FROM THE CLOCK, never accumulated. That is
// the whole trick, and it is the only reason every client agrees.
//
// The engine's own tween is an integrator: it adds `delta_secs * 1000 /
// duration` every frame and clamps at 1. Two peers running that loop lose a
// different amount of phase at every leg boundary — the slower peer loses more,
// always in the same direction — so their platforms drift apart without bound
// and nothing in the engine ever pulls them back together.
//
// So we never let the engine decide which leg it is in. The leg table is a
// fixed cycle anchored to the Unix epoch, `legPhaseAt` answers "which leg, how
// far through" as a pure function of server-clock time, and the caller writes
// that answer into the tween's `currentTime` — which the renderer honours as an
// exact seek. Every peer computes the same answer from the same clock, so the
// per-leg debt is deleted rather than reset.
//
// Anchoring to the epoch (not to a start event) is what makes a late joiner and
// a restarted server land on the same phase without being told anything.

export type Easing = 'linear' | 'smooth'

export interface Leg {
  durationMs: number
  /** false = the platform waits here. A wait is a leg, so it stays in phase. */
  moving: boolean
  /** Index into the caller's stop list. */
  from: number
  to: number
}

export interface LegPhase {
  index: number
  leg: Leg
  /** 0..1 through this leg, BEFORE easing — this is what `currentTime` wants. */
  progress: number
  /** Server-clock ms this leg began. Identity for "still the same leg". */
  startedAtMs: number
}

export type PathMode = 'back and forth' | 'around' | 'once'

/** A there-and-back cycle: out, wait, back, wait. */
export function shuttleLegs(travelMs: number, waitMs: number): Leg[] {
  return pathLegs(2, travelMs, waitMs, 'back and forth')
}

/**
 * The leg table for a path over `stops` points, one `travelMs` leg between
 * consecutive stops, `waitMs` at every arrival.
 *
 *   'back and forth'  0→1→…→N-1 then back down to 0, forever
 *   'around'          0→1→…→N-1→0, forever (needs 3+ stops to differ)
 *   'once'            0→1→…→N-1, then parked — NOT a cycle; pair with
 *                     `legPhaseAt(..., { cyclic: false })`
 */
export function pathLegs(stops: number, travelMs: number, waitMs: number, mode: PathMode): Leg[] {
  const travel = Math.max(1, Math.round(travelMs))
  const wait = Math.max(0, Math.round(waitMs))
  const count = Math.max(2, Math.trunc(stops))
  const legs: Leg[] = []
  const move = (from: number, to: number): void => {
    legs.push({ durationMs: travel, moving: true, from, to })
  }
  const rest = (at: number): void => {
    if (wait > 0) legs.push({ durationMs: wait, moving: false, from: at, to: at })
  }
  if (mode === 'once') {
    for (let i = 0; i < count - 1; i++) {
      move(i, i + 1)
      if (i < count - 2) rest(i + 1)
    }
    return legs
  }
  if (mode === 'around') {
    for (let i = 0; i < count; i++) {
      move(i, (i + 1) % count)
      rest((i + 1) % count)
    }
    return legs
  }
  for (let i = 0; i < count - 1; i++) {
    move(i, i + 1)
    rest(i + 1)
  }
  for (let i = count - 1; i > 0; i--) {
    move(i, i - 1)
    rest(i - 1)
  }
  return legs
}

export function cycleMsOfLegs(legs: readonly Leg[]): number {
  let total = 0
  for (const leg of legs) total += Math.max(0, leg.durationMs)
  return total
}

/**
 * Which leg is `nowMs` in, and how far through. Pure, O(legs), and identical on
 * every peer that passes the same server-clock reading.
 *
 * `cyclic: false` treats the table as a one-shot run from the anchor: before
 * the anchor the platform rests at the first leg's start, after the table has
 * played out it parks on the last leg at progress 1.
 *
 * Returns null for a table that cannot describe a cycle — the caller should
 * leave the platform alone rather than guess.
 */
export function legPhaseAt(
  legs: readonly Leg[],
  nowMs: number,
  epochMs = 0,
  opts: { cyclic?: boolean } = {}
): LegPhase | null {
  const cycleMs = cycleMsOfLegs(legs)
  if (legs.length === 0 || cycleMs <= 0 || !Number.isFinite(nowMs)) return null

  const sinceEpoch = nowMs - epochMs
  if (opts.cyclic === false) {
    const first = legs.findIndex((leg) => leg.durationMs > 0)
    if (first < 0) return null
    if (sinceEpoch <= 0) {
      return { index: first, leg: legs[first], progress: 0, startedAtMs: epochMs }
    }
    if (sinceEpoch >= cycleMs) return parkedAtEnd(legs, epochMs, cycleMs)
  }

  // Floor-modulo: a client whose clock sits behind the epoch is still in phase.
  const intoCycle = ((sinceEpoch % cycleMs) + cycleMs) % cycleMs
  const cycleStartMs = nowMs - intoCycle

  let offsetMs = 0
  for (let index = 0; index < legs.length; index++) {
    const leg = legs[index]
    const durationMs = Math.max(0, leg.durationMs)
    if (durationMs === 0) continue
    if (intoCycle < offsetMs + durationMs) {
      const elapsedMs = intoCycle - offsetMs
      return {
        index,
        leg,
        progress: clamp01(elapsedMs / durationMs),
        startedAtMs: cycleStartMs + offsetMs
      }
    }
    offsetMs += durationMs
  }

  // Floating-point landing exactly on the cycle end: report the last real leg
  // complete rather than returning null on one frame in millions.
  return parkedAtEnd(legs, cycleStartMs, cycleMs)
}

/** The last leg with any duration, complete, in the cycle starting at `cycleStartMs`. */
function parkedAtEnd(legs: readonly Leg[], cycleStartMs: number, cycleMs: number): LegPhase | null {
  for (let index = legs.length - 1; index >= 0; index--) {
    const leg = legs[index]
    if (leg.durationMs > 0) {
      return { index, leg, progress: 1, startedAtMs: cycleStartMs + cycleMs - leg.durationMs }
    }
  }
  return null
}

export function clamp01(value: number): number {
  if (!Number.isFinite(value)) return 0
  return Math.min(1, Math.max(0, value))
}

/** Mirrors the engine's EF_EASEQUAD (quadratic in-out). */
export function easeQuadInOut(t: number): number {
  const x = clamp01(t)
  return x < 0.5 ? 2 * x * x : 1 - 2 * (1 - x) * (1 - x)
}

/** Fraction of the path travelled at raw progress `t`. Monotonic in `t`. */
export function easedAt(t: number, easing: Easing): number {
  return easing === 'smooth' ? easeQuadInOut(t) : clamp01(t)
}

/**
 * Raw progress that lands at eased fraction `value`. Bisection rather than a
 * closed form so adding an easing here cannot silently produce a wrong inverse.
 */
export function progressForEased(value: number, easing: Easing): number {
  const target = clamp01(value)
  if (easing === 'linear') return target
  let low = 0
  let high = 1
  for (let step = 0; step < 24; step++) {
    const mid = (low + high) / 2
    if (easedAt(mid, easing) < target) low = mid
    else high = mid
  }
  return (low + high) / 2
}

/**
 * A seek that cannot throw a rider off. The engine carries a player only while
 * the deck moves less than 5 world units in one frame — past that it SKIPS the
 * carry entirely and leaves them standing in the air. So a correction never
 * jumps further than `maxUnits`; it converges over a few frames instead.
 *
 * Both progresses are raw; the distance between them is measured AFTER easing,
 * because that is what the deck actually does.
 */
export function clampSeek(
  fromProgress: number,
  toProgress: number,
  pathUnits: number,
  maxUnits: number,
  easing: Easing
): number {
  const target = clamp01(toProgress)
  if (!(pathUnits > 0) || !(maxUnits > 0)) return target
  const current = clamp01(fromProgress)
  const currentEased = easedAt(current, easing)
  const targetEased = easedAt(target, easing)
  const jumpUnits = Math.abs(targetEased - currentEased) * pathUnits
  if (jumpUnits <= maxUnits) return target
  const step = maxUnits / pathUnits
  const cappedEased = targetEased > currentEased ? currentEased + step : currentEased - step
  return progressForEased(cappedEased, easing)
}
