// Generated by Decentraland Studio. Do not edit: this copy is kept in sync with your editor version.
// The pure heart of the `game` module: message dispatch, direction rules,
// per-name FIFO, rate limits, payload hygiene, presence and zone verification.
// No SDK imports — the SDK-facing half (game.ts) wires these ports to the real
// transport; the harness wires them to a simulated world. Everything testable
// lives here.

import { rotateVec, type Quat, type Vec3 } from './worldTransform'
import { zoneKey } from './zoneRegistry'

export type { Quat, Vec3 }

export type Player = string

export type ErrorSide = 'game' | 'you'

export interface ErrorCard {
  side: ErrorSide
  name: string
  message: string
}

export interface CorePorts {
  now(): number
  /** blue → green: correlated ask, resolves with the handler's JSON reply */
  sendAsk(name: string, json: string): Promise<string>
  /** green → screens: fire a tell, all screens or one player */
  sendTell(name: string, json: string, to?: Player): void
  /** green only: publish one shared fact (SDK half: a protectSynced SharedFact
   * entity per key; harness: the world's fact store). Reliable, snapshotted —
   * late joiners receive every fact without any message. */
  publishFact(key: string, json: string, rev: number): void
  /** green only, boot: retire a stale fact that survived the last run's
   * snapshot. SDK half: remove the entity (defer-a-tick rule applies there). */
  retireFact(key: string, rev: number): void
  /** surface an error card ([game] / [you]) — never silent */
  emitError(card: ErrorCard): void
  /** dev-Play warning (size budgets etc.) — never an error, never silent */
  devWarn(message: string): void
  /** boot: the saved record that survived sleep (serverState-backed in the
   * SDK half; the harness: a store that outlives restarts, unlike facts) */
  loadSaved(): Promise<Record<string, unknown>>
  /** green write-behind: hand one saved key to the persistence layer — it
   * checkpoints (round end, player leave), never per tick */
  storeSaved(key: string, value: unknown): void
  /** boot/join: one player's durable record ({} on a first visit) */
  loadPlayerData(player: Player): Promise<Record<string, unknown>>
  /** green write-behind: the player's whole record, checkpointed like saved */
  storePlayerData(player: Player, data: Record<string, unknown>): void
  /** leave checkpoint: write this player's pending record now — the debounce
   * window would outlive their visit */
  flushPlayerData(player: Player): void
  /** leave checkpoint: drop the transport's per-player memory (the replay cache
   * for their request ids), so a full room costs no more than the room */
  dropPlayer(player: Player): void
  /** server: every volume carrying this zone key — [] when no such zone is placed */
  findZones(zoneKey: string): ZoneVolume[]
  /** server: a player's feet in scene coords, null until comms delivers their avatar */
  playerPosition(player: Player): Vec3 | null
  /** server: the seed committed for the round being started. Drawn ahead into
   * server-private state (serverState in the SDK half — never synced, throws on
   * a client) and replaced with a fresh draw on every take, so no client can
   * precompute a layout before its round starts (§11 seed secrecy). */
  takeNextSeed(): number
}

// §11 hardening defaults. Tunable per handler later; the caps are checked
// before dispatch so malformed or oversized input never reaches creator code.
const RATE_PER_S = 8
export const MAX_PAYLOAD_BYTES = 4096
const MAX_PAYLOAD_DEPTH = 8
// Per-key state size guard: one SharedFact must stay far from the transport's
// 12 KB chunk edge. Warn, don't block — the creator may be mid-refactor.
const FACT_WARN_BYTES = 4096
// §11.2: one player must not bloat the isolate or the Storage budget.
export const PLAYER_DATA_CAP_BYTES = 8192
// Zone verification (ported from zone-authority): positions arrive at ≤10 Hz
// and are the avatar's FEET while the real collider is a 2 m capsule, so an
// honest player standing on the boundary must not be called a cheat.
const ZONE_SLACK_M = 1
// A member whose position the server cannot see at all (still loading, comms
// hiccup) keeps their place this long before the sweep gives up on them.
const ZONE_LOST_GRACE_MS = 10_000
// Zone claims are edge-triggered by the client's own zone bus, so an honest
// player sends a couple per zone per visit; the sweep re-checks at 4 Hz anyway.
const ZONE_CLAIMS_PER_S = 4

export interface ZoneVolume {
  shape: 'box' | 'sphere'
  center: Vec3
  rotation: Quat
  scale: Vec3
}

// Same volume definition the engine uses (ADR-258): a UNIT box or sphere scaled
// by the entity's world transform; `slack` widens every half-extent by metres.
// The point moves into the volume's own frame (inverse rotation about the
// centre); scale stays in the half-extents, which keeps non-uniform scale exact.
function insideZone(volume: ZoneVolume, point: Vec3, slack: number): boolean {
  const { center, rotation, scale } = volume
  if (scale.x <= 0 || scale.y <= 0 || scale.z <= 0) return false
  const margin = slack > 0 ? slack : 0
  const half = { x: scale.x / 2 + margin, y: scale.y / 2 + margin, z: scale.z / 2 + margin }
  const inverse = { x: -rotation.x, y: -rotation.y, z: -rotation.z, w: rotation.w }
  const local = rotateVec(inverse, { x: point.x - center.x, y: point.y - center.y, z: point.z - center.z })
  if (volume.shape === 'sphere') {
    const x = local.x / half.x
    const y = local.y / half.y
    const z = local.z / half.z
    return x * x + y * y + z * z <= 1
  }
  return Math.abs(local.x) <= half.x && Math.abs(local.y) <= half.y && Math.abs(local.z) <= half.z
}

// The round tuple (§2.2): the numbers every screen reconstructs a round from,
// plus the monotonic round number real games key per-round validity on (§12 #2).
// It rides game.state under one reserved key, so a late joiner gets the current
// round from the snapshot like any other fact — no second mechanism.
const ROUND_STATE_KEY = 'round'

export interface RoundInfo {
  number: number
  seed: number
  phase: number
  phaseStartMs: number
  configVersion: number
}

function zeroRound(): RoundInfo {
  return { number: 0, seed: 0, phase: 0, phaseStartMs: 0, configVersion: 0 }
}

/** Defensive read: the tuple crossed the wire, and a creator can clobber the
 * reserved key — a corrupt field must not poison every derived layout. */
function asRoundInfo(value: unknown): RoundInfo {
  if (typeof value !== 'object' || value === null) return zeroRound()
  const record = value as Record<string, unknown>
  const read = (key: keyof RoundInfo): number => {
    const raw = record[key]
    return typeof raw === 'number' && Number.isFinite(raw) ? Math.floor(raw) : 0
  }
  const number = read('number')
  if (number <= 0) return zeroRound()
  return {
    number,
    seed: read('seed'),
    phase: read('phase'),
    phaseStartMs: read('phaseStartMs'),
    configVersion: read('configVersion')
  }
}

/** One rng stream per (round seed, prefab): two layouts sharing a round must
 * not share draws (the draw-order contract, rng.ts rule 1). */
export function layoutSeed(seed: number, prefab: string): number {
  let h = seed | 0
  for (let i = 0; i < prefab.length; i++) h = (Math.imul(h, 31) + prefab.charCodeAt(i)) | 0
  return h
}

// The Game Config version pinned into the tuple, published by the generated
// src/scripts/game-config.ts on globalThis — the only channel a carried module
// copy can read it through (the round-loop precedent).
function configVersionNow(): number {
  const bag = (globalThis as unknown as Record<string, unknown>).__dclGameConfig_v1
  const version = typeof bag === 'object' && bag !== null ? (bag as Record<string, unknown>).version : undefined
  return typeof version === 'number' && Number.isFinite(version) && version >= 0 ? Math.floor(version) : 0
}

// Message tracing: off unless a scene turns it on (game.trace(true), or set
// __dclGameTrace_v1 from the console mid-session). Every line names the copy
// that printed it, the direction, the message and its size, so a creator can
// watch the whole conversation between the game and the screens.
const TRACE_KEY = '__dclGameTrace_v1'

export function setTrace(on: boolean): void {
  ;(globalThis as unknown as Record<string, unknown>)[TRACE_KEY] = on
}

function tracing(): boolean {
  return (globalThis as unknown as Record<string, unknown>)[TRACE_KEY] === true
}

export function trace(side: ErrorSide, arrow: string, name: string, json?: string, note?: string): void {
  if (!tracing()) return
  const size = json === undefined ? '' : ` ${json.length}B`
  const body = json === undefined || json === '{}' ? '' : ` ${json.length > 120 ? `${json.slice(0, 120)}…` : json}`
  console.log(`[${side}] ${arrow} ${name}${size}${note === undefined ? '' : ` (${note})`}${body}`)
}

const SET_STATE_GUARD = 'Only the server can change game.state. Move this inside game.onMessage.'
const ROUND_KEY_GUARD = "game.state.round is the round itself. Use game.newRound(), or pick another name."
const SAVED_READ_GUARD = 'Only the server can read saved data. Move this inside game.onMessage.'
const SAVED_WRITE_GUARD = 'Only the server can change saved data. Move this inside game.onMessage.'
const PLAYER_DATA_READ_GUARD = 'Only the server can read player data. Move this inside game.onMessage.'
const PLAYER_DATA_WRITE_GUARD = 'Only the server can change player data. Move this inside game.onMessage.'
const POSITION_GUARD = 'Only the server can read player positions. Move this inside game.onMessage.'
const NEW_ROUND_GUARD = 'Only the server can start a round. Move this inside game.onMessage.'

type Direction = 'ask' | 'tell'
type Handler = (data: unknown, player: Player) => unknown | Promise<unknown>

interface HandlerEntry {
  fn: Handler
  scriptId: string
}

export class GameNameError extends Error {
  constructor(name: string, nearest: string | null) {
    super(
      nearest
        ? `No handler named '${name}'. Closest match: '${nearest}'.`
        : `No handler named '${name}'. Register it with game.onMessage('${name}', …).`
    )
    this.name = 'GameNameError'
  }
}

export class GameDirectionError extends Error {
  constructor(name: string, claimed: Direction) {
    super(
      claimed === 'ask'
        ? `'${name}' is asked by players — the server can't send it. Use a different name to tell players.`
        : `'${name}' is sent by the server — a player can't ask it. Use a different name to ask the server.`
    )
    this.name = 'GameDirectionError'
  }
}

export function jsonDepth(value: unknown, limit: number): number {
  if (value === null || typeof value !== 'object') return 0
  let max = 1
  for (const v of Object.values(value as Record<string, unknown>)) {
    if (v !== null && typeof v === 'object') {
      const d = 1 + jsonDepth(v, limit - 1)
      if (d > max) max = d
      if (max > limit) return max
    }
  }
  return max
}

interface Bucket {
  tokens: number
  atMs: number
}

export class RateLimiter {
  private buckets = new Map<string, Bucket>()
  constructor(private ratePerS: number = RATE_PER_S) {}

  allow(name: string, player: Player, nowMs: number): boolean {
    const key = `${name}\0${player}`
    const b = this.buckets.get(key) ?? { tokens: this.ratePerS, atMs: nowMs }
    b.tokens = Math.min(this.ratePerS, b.tokens + ((nowMs - b.atMs) / 1000) * this.ratePerS)
    b.atMs = nowMs
    if (b.tokens < 1) {
      this.buckets.set(key, b)
      return false
    }
    b.tokens -= 1
    this.buckets.set(key, b)
    return true
  }
}

// Levenshtein-lite: good enough to say "closest match" in a typo error.
function editDistance(a: string, b: string): number {
  if (Math.abs(a.length - b.length) > 3) return 99
  const dp = Array.from({ length: a.length + 1 }, (_, i) => i)
  for (let j = 1; j <= b.length; j++) {
    let prev = dp[0]
    dp[0] = j
    for (let i = 1; i <= a.length; i++) {
      const cur = dp[i]
      dp[i] = Math.min(dp[i] + 1, dp[i - 1] + 1, prev + (a[i - 1] === b[j - 1] ? 0 : 1))
      prev = cur
    }
  }
  return dp[a.length]
}

type StateListener = (changed: Record<string, unknown>) => void
type PresenceFn = (player: Player) => void | Promise<void>
export type ZoneClaimKind = 'enter' | 'exit'
export interface ZoneClaimReply {
  ok: boolean
  verified: boolean
}

export class GameCore {
  // One registry serves both roles: on the game a handler hears asks, on a
  // screen the same registration hears tells — which side runs is the fork.
  private handlers = new Map<string, HandlerEntry>()
  private directions = new Map<string, Direction>()
  private queues = new Map<string, Promise<void>>()
  private limiter = new RateLimiter()
  private zoneLimiter = new RateLimiter(ZONE_CLAIMS_PER_S)
  private server: boolean | null = null

  // Shared facts: the state mirror every side reads; only green code writes.
  // Each top-level key becomes its own published fact (per-key sharding keeps
  // any single write far from the chunk edge and lets unrelated keys move
  // independently). Writes coalesce: at most one publish per key per tick.
  readonly state: Record<string, unknown> = {}
  private revs = new Map<string, number>()
  private dirty = new Map<string, unknown>()
  private stateListeners: StateListener[] = []
  // Teaching guard, not a security boundary: above zero while green code runs.
  // Across an awaited span a concurrently ticking update() would pass it —
  // acceptable, documented, never described as airtight.
  //
  // A COUNT, not a flag: newRound() deliberately runs the round-start hooks in a
  // microtask outside the caller's own span, so two spans overlap by design. With
  // a flag, the outer span's finally clears it the moment the inner span awaits,
  // and the next hook in line is told only the game may write state — which is
  // exactly the Game-Flow-plus-a-script arrangement the kit ships.
  private greenSpans = 0
  private hasBooted = false
  // Durable memory: replaced by the boot restore before any green code runs
  // (handlers queue until boot; onStart runs after the restore).
  private savedData: Record<string, unknown> = {}
  private playerRecords = new Map<Player, Record<string, unknown>>()
  private playerLoads = new Map<Player, Promise<void>>()
  /** writes for players whose record is not in memory, waiting on their load */
  private pendingPatches = new Map<Player, Record<string, unknown>>()
  private onStartFns: Array<() => void | Promise<void>> = []
  private roundStartFns: Array<(round: RoundInfo) => void | Promise<void>> = []
  private preBootAsks: Array<{
    name: string
    json: string
    from: Player
    resolve: (json: string) => void
    reject: (e: Error) => void
  }> = []
  // Presence: the wallets the server currently sees, diffed every tick against
  // the synced identity roster the SDK half enumerates.
  private present = new Set<Player>()
  private joinFns: PresenceFn[] = []
  private leaveFns: PresenceFn[] = []
  // Zones: zone key → verified members. The value is the ms at which the sweep
  // lost sight of that member's position, 0 while it can see them.
  private zoneMembers = new Map<string, Map<Player, number>>()
  private zoneEnterFns = new Map<string, PresenceFn[]>()
  private zoneExitFns = new Map<string, PresenceFn[]>()
  private preBootZoneClaims: Array<{
    zone: string
    kind: ZoneClaimKind
    player: Player
    resolve: (reply: ZoneClaimReply) => void
    reject: (e: Error) => void
  }> = []

  constructor(private ports: CorePorts) {}

  /** The platform resolves the role async; until then registrations queue. */
  setRole(isServer: boolean): void {
    this.server = isServer
  }

  isServer(): boolean {
    return this.server === true
  }

  private claimDirection(name: string, dir: Direction): void {
    const claimed = this.directions.get(name)
    if (claimed === undefined) {
      this.directions.set(name, dir)
      return
    }
    if (claimed !== dir) throw new GameDirectionError(name, claimed)
  }

  private nearestName(name: string): string | null {
    let best: string | null = null
    let bestD = 3
    for (const known of this.handlers.keys()) {
      const d = editDistance(name, known)
      if (d < bestD) {
        bestD = d
        best = known
      }
    }
    return best
  }

  /**
   * game.onMessage(name, fn): role-agnostic registration. On the server it
   * hears the messages players send; on a screen it hears the messages the
   * server sends. One handler per name — re-registering from the same script
   * replaces (a prefab placed twice shares one handler); a different script
   * claiming the name errors.
   */
  onMessage(name: string, fn: Handler, scriptId: string): void {
    const existing = this.handlers.get(name)
    if (existing && existing.scriptId !== scriptId) {
      throw new Error(
        `Two scripts both handle '${name}' (${existing.scriptId} and ${scriptId}). One name has one handler — use a different name.`
      )
    }
    this.handlers.set(name, { fn, scriptId })
  }

  /** Blue send: ask the game. Green send: tell the players. */
  async send(name: string, data: unknown, opts?: { to?: Player }): Promise<unknown> {
    const json = JSON.stringify(data ?? {})
    if (this.isServer()) {
      // The game's own code decides a name's direction — an inbound ask that
      // arrived first is corrected here, not obeyed. It still warns: one name
      // used both ways is a creator mistake the edit-time check should catch.
      if (this.directions.get(name) === 'ask') {
        this.ports.devWarn(`'${name}' is used both ways — players ask it and the game sends it. Use two names.`)
      }
      this.directions.set(name, 'tell')
      trace('game', '→ screens', name, json, opts?.to === undefined ? undefined : `only ${opts.to}`)
      this.ports.sendTell(name, json, opts?.to)
      return undefined
    }
    this.claimDirection(name, 'ask')
    trace('you', '→ game', name, json)
    const reply = await this.ports.sendAsk(name, json)
    trace('you', '← game', name, reply, 'reply')
    return reply === '' ? null : JSON.parse(reply)
  }

  /**
   * Server dispatch of an incoming ask: hygiene first (rate, size, depth),
   * then the per-name FIFO — awaited, crash-contained. The reply is the
   * handler's return, JSON-encoded; hygiene rejections and unknown names
   * reject the ask so the sender's await fails loudly, never silently.
   */
  handleAsk(name: string, json: string, from: Player): Promise<string> {
    if (!this.hasBooted) {
      // waking: asks queue instead of failing — drained at the end of boot
      return new Promise<string>((resolve, reject) => {
        this.preBootAsks.push({ name, json, from, resolve, reject })
      })
    }
    // Nothing off the wire may claim a direction: an unknown or screen-side
    // name must be refused WITHOUT touching the registry, or one forged packet
    // both runs screen code in the game and kills that name for the session.
    const entry = this.handlers.get(name)
    if (!entry) return Promise.reject(new GameNameError(name, this.nearestName(name)))
    if (this.directions.get(name) === 'tell') {
      return Promise.reject(new Error(`'${name}' is sent by the server — players can't ask it.`))
    }
    this.directions.set(name, 'ask')
    if (!this.limiter.allow(name, from, this.ports.now())) {
      this.ports.emitError({ side: 'game', name, message: `'${name}' from ${from} dropped — too many per second.` })
      return Promise.reject(new Error(`'${name}' dropped — asked too often. Send it less often.`))
    }
    if (json.length > MAX_PAYLOAD_BYTES) {
      return Promise.reject(new Error(`'${name}' carries too much data — send less than ${MAX_PAYLOAD_BYTES} bytes.`))
    }
    let data: unknown
    try {
      data = json === '' ? undefined : JSON.parse(json)
    } catch {
      return Promise.reject(new Error(`'${name}' payload is not valid JSON.`))
    }
    if (jsonDepth(data, MAX_PAYLOAD_DEPTH) > MAX_PAYLOAD_DEPTH) {
      return Promise.reject(new Error(`'${name}' is nested too deep — use a simpler object.`))
    }

    // The chain orders one name's handlers; it must never carry a failure
    // forward, or one rejected ask would stop every later ask on that name.
    trace('game', '← you', name, json, from)
    const prev = (this.queues.get(name) ?? Promise.resolve()).catch(() => {})
    let result: unknown
    let failed: Error | null = null
    const run = prev.then(async () => {
      this.greenSpans += 1
      try {
        result = await entry.fn(data, from)
      } catch (e) {
        failed = e instanceof Error ? e : new Error(String(e))
        this.ports.emitError({ side: 'game', name, message: `${entry.scriptId}: ${failed.message}` })
      } finally {
        this.greenSpans -= 1
        this.flushState()
      }
    })
    this.queues.set(name, run)
    return run.then(() => {
      if (failed) throw failed
      return JSON.stringify(result ?? null)
    })
  }

  // Teaching guard for everything only green code may touch — same caveat as
  // greenSpans: not airtight across awaits, never claimed to be.
  private greenGuard(message: string): void {
    if (!this.isServer() || this.greenSpans === 0) throw new Error(message)
  }

  /** game.setState — green handlers only. Values land in the mirror at once
   * (a handler reads its own writes) and publish coalesced on flush. */
  setState(patch: Record<string, unknown>): void {
    this.greenGuard(SET_STATE_GUARD)
    for (const [key, value] of Object.entries(patch)) {
      if (key === ROUND_STATE_KEY) throw new Error(ROUND_KEY_GUARD)
      this.state[key] = value
      this.dirty.set(key, value)
    }
  }

  onStateChange(listener: StateListener): void {
    this.stateListeners.push(listener)
  }

  /** Server: publish dirty keys — at most one write per key per flush. Called
   * after every green handler and from the SDK half's engine tick. */
  flushState(): void {
    if (!this.isServer() || this.dirty.size === 0) return
    try {
      for (const [key, value] of this.dirty) {
        let json: string
        try {
          json = JSON.stringify(value ?? null)
        } catch {
          // a value JSON can't carry (a BigInt, a cycle) must cost one key, not
          // the frame: publishing runs from an engine system and a finally block
          this.state[key] = undefined
          this.ports.emitError({
            side: 'game',
            name: `state.${key}`,
            message: `game.state.${key} can't be shared — use plain numbers, strings, booleans, arrays and objects.`
          })
          continue
        }
        if (json.length > FACT_WARN_BYTES) {
          this.ports.devWarn(`game.state.${key} is over ${FACT_WARN_BYTES} bytes — split it into smaller keys.`)
        }
        const rev = (this.revs.get(key) ?? 0) + 1
        this.revs.set(key, rev)
        try {
          trace('game', '→ state', key, json, `rev ${rev}`)
          this.ports.publishFact(key, json, rev)
        } catch (e) {
          this.ports.emitError({
            side: 'game',
            name: `state.${key}`,
            message: `game.state.${key} could not be shared this time: ${e instanceof Error ? e.message : String(e)}`
          })
        }
      }
    } finally {
      this.dirty.clear()
    }
  }

  /** Client: one shared fact arrived (live change or snapshot). Stale revs —
   * a re-delivered snapshot behind the live stream — are dropped. */
  applyFact(key: string, json: string, rev: number): void {
    const known = this.revs.get(key) ?? 0
    if (rev <= known) return
    this.revs.set(key, rev)
    let value: unknown
    try {
      value = JSON.parse(json)
    } catch {
      this.ports.emitError({ side: 'you', name: `state.${key}`, message: 'synced state arrived with invalid JSON.' })
      return
    }
    this.state[key] = value
    trace('you', '← state', key, json, `rev ${rev}`)
    const changed = { [key]: value }
    for (const listener of this.stateListeners) {
      try {
        listener(changed)
      } catch (e) {
        this.ports.emitError({ side: 'you', name: `state.${key}`, message: e instanceof Error ? e.message : String(e) })
      }
    }
  }

  /** Client: a fact was retired (boot wipe). The key leaves the mirror. */
  applyRetire(key: string, rev: number): void {
    const known = this.revs.get(key) ?? 0
    if (rev <= known) return
    this.revs.set(key, rev)
    if (!(key in this.state)) return
    delete this.state[key]
    const changed = { [key]: undefined }
    for (const listener of this.stateListeners) {
      try {
        listener(changed)
      } catch (e) {
        this.ports.emitError({ side: 'you', name: `state.${key}`, message: e instanceof Error ? e.message : String(e) })
      }
    }
  }

  /** game.saved — survives restarts and re-publishes, unlike game.state.
   * Green only, both directions; change values through set (a reference
   * mutated in place never reaches the persistence layer). */
  readonly saved = {
    get: (key: string): unknown => {
      this.greenGuard(SAVED_READ_GUARD)
      return this.savedData[key]
    },
    set: (key: string, value: unknown): void => {
      this.greenGuard(SAVED_WRITE_GUARD)
      this.savedData[key] = value
      this.ports.storeSaved(key, value)
    }
  }

  /** game.playerData(player) — the per-wallet durable record. Green only;
   * set patches top-level keys (the setState shape), capped per player. */
  playerData(player: Player): {
    get(): Record<string, unknown>
    set(patch: Record<string, unknown>): void
  } {
    return {
      get: () => {
        this.greenGuard(PLAYER_DATA_READ_GUARD)
        return this.playerRecord(player)
      },
      set: (patch) => {
        this.greenGuard(PLAYER_DATA_WRITE_GUARD)
        // Writing on top of a record we have not loaded would turn a patch
        // into a replace and wipe everything that player earned before today.
        // A round-end tally naming someone who just logged off is ordinary,
        // so the patch waits for their record to load and lands on top of it.
        const loaded = this.playerRecords.get(player)
        if (!loaded) {
          this.queuePlayerPatch(player, patch)
          return
        }
        const next = { ...loaded, ...patch }
        const bytes = JSON.stringify(next).length
        if (bytes > PLAYER_DATA_CAP_BYTES) {
          throw new Error(
            `playerData for ${player} would be ${bytes} bytes — the cap is ${PLAYER_DATA_CAP_BYTES}. Store less per player.`
          )
        }
        this.playerRecords.set(player, next)
        this.ports.storePlayerData(player, next)
      }
    }
  }

  // A player who left has no record in memory — reading theirs at round end is
  // ordinary (they logged off mid-round), so it reads as a first visit does
  // rather than throwing and aborting the caller's remaining work.
  private playerRecord(player: Player): Record<string, unknown> {
    return this.playerRecords.get(player) ?? {}
  }

  /**
   * A write for a player whose record is not in memory: hold the patch, load
   * what they have, then apply it on top and hand it to storage. The record is
   * evicted again afterwards — they are gone, so nothing should keep growing
   * on their behalf.
   */
  private queuePlayerPatch(player: Player, patch: Record<string, unknown>): void {
    const pending = this.pendingPatches.get(player)
    if (pending) {
      Object.assign(pending, patch)
      return
    }
    this.pendingPatches.set(player, { ...patch })
    void this.ports
      .loadPlayerData(player)
      .then((stored) => {
        const queued = this.pendingPatches.get(player) ?? {}
        const next = { ...stored, ...queued }
        const bytes = JSON.stringify(next).length
        if (bytes > PLAYER_DATA_CAP_BYTES) {
          this.ports.emitError({
            side: 'game',
            name: 'playerData',
            message: `playerData for ${player} would be ${bytes} bytes — the cap is ${PLAYER_DATA_CAP_BYTES}. Store less per player.`
          })
          return
        }
        this.ports.storePlayerData(player, next)
      })
      .catch((e: unknown) => {
        this.ports.emitError({
          side: 'game',
          name: 'playerData',
          message: `couldn't save data for a player who left: ${e instanceof Error ? e.message : String(e)}`
        })
      })
      .finally(() => this.pendingPatches.delete(player))
  }

  /** Awaited by the SDK half before a player's first green handler (and by
   * bootServer for players already present), so .get() never races the load. */
  async restorePlayerData(player: Player): Promise<void> {
    if (this.playerRecords.has(player)) return
    // N asks in one tick must cost one storage read, not N: the host-call
    // budget is scene-wide, and blowing it makes every player's writes fail
    const inFlight = this.playerLoads.get(player)
    if (inFlight) return inFlight
    const load = this.ports
      .loadPlayerData(player)
      .then((data) => {
        // a green set may have landed across the await — never clobber it
        if (!this.playerRecords.has(player)) this.playerRecords.set(player, data)
      })
      .finally(() => this.playerLoads.delete(player))
    this.playerLoads.set(player, load)
    return load
  }

  /** game.onStart — the green boot hook: runs once when the game wakes up
   * (not per player, not per round), after restart cleanup. */
  onStart(fn: () => void | Promise<void>): void {
    this.onStartFns.push(fn)
  }

  booted(): boolean {
    return this.hasBooted
  }

  /**
   * The server boot pipeline, in the honest order: re-adopt the facts that
   * survived the last run's snapshot (seeding revs so every fresh publish
   * OUTRUNS the stale copy a connected screen still holds) → retire them —
   * state resets when the game sleeps → restore durable memory (saved, plus
   * playerData for the players already present) so onStart can copy saved
   * back in for continuity → run the green onStart hooks → flush → open for
   * asks and drain anything that queued while waking.
   */
  async bootServer(
    adopted: Array<{ key: string; json: string; rev: number }>,
    players: Player[] = []
  ): Promise<void> {
    if (this.hasBooted) return
    for (const fact of adopted) {
      const rev = fact.rev + 1
      this.revs.set(fact.key, rev)
      this.ports.retireFact(fact.key, rev)
    }
    this.savedData = await this.ports.loadSaved()
    await Promise.all(players.map((p) => this.restorePlayerData(p)))
    await this.runGreen('onStart', this.onStartFns)
    // Round 1 starts at boot (unless an onStart hook already called newRound):
    // layouts exist from the first frame, and the round-1 reset runs like any
    // other round's. The counter resets with the state, per the §5 lifetimes.
    if (this.round.number === 0) {
      await this.runGreen('onRoundStart', this.roundStartFns, this.beginRound(1))
    }
    this.hasBooted = true
    const queued = this.preBootAsks
    this.preBootAsks = []
    for (const q of queued) {
      // handleAsk rejects synchronously on a bad name: one queued ask must
      // never abort the drain and leave the rest of the queue unanswered
      try {
        this.handleAsk(q.name, q.json, q.from).then(q.resolve, q.reject)
      } catch (e) {
        q.reject(e instanceof Error ? e : new Error(String(e)))
      }
    }
    const claims = this.preBootZoneClaims
    this.preBootZoneClaims = []
    for (const c of claims) {
      this.zoneClaim(c.zone, c.kind, c.player).then(c.resolve, c.reject)
    }
  }

  // One green span, shared by every callback family: errors surface as a
  // [game] card and never wedge the caller; dirty state flushes on the way out.
  private async runGreen<A extends unknown[]>(
    name: string,
    fns: ReadonlyArray<(...args: A) => unknown>,
    ...args: A
  ): Promise<void> {
    this.greenSpans += 1
    try {
      for (const fn of fns) {
        try {
          await fn(...args)
        } catch (e) {
          this.ports.emitError({ side: 'game', name, message: e instanceof Error ? e.message : String(e) })
        }
      }
    } finally {
      this.greenSpans -= 1
      this.flushState()
    }
  }

  /** game.onPlayerJoin — runs in the game when a player arrives. */
  onPlayerJoin(fn: PresenceFn): void {
    this.joinFns.push(fn)
  }

  /** game.onPlayerLeave — runs in the game when a player leaves. */
  onPlayerLeave(fn: PresenceFn): void {
    this.leaveFns.push(fn)
  }

  /**
   * Server tick input: every wallet the engine can currently see. The diff
   * against the last roster IS join/leave — SDK onEnterScene never fires on
   * the headless server, so the synced identity set is the only truth.
   */
  presentPlayers(present: Player[]): void {
    if (!this.isServer() || !this.hasBooted) return
    const now = new Set(present)
    for (const player of now) {
      if (this.present.has(player)) continue
      this.present.add(player)
      void this.playerJoined(player)
    }
    for (const player of [...this.present]) {
      if (now.has(player)) continue
      this.present.delete(player)
      void this.playerLeft(player)
    }
  }

  private async playerJoined(player: Player): Promise<void> {
    await this.restorePlayerData(player)
    await this.runGreen('onPlayerJoin', this.joinFns, player)
  }

  private async playerLeft(player: Player): Promise<void> {
    for (const key of [...this.zoneMembers.keys()]) this.dropZoneMember(key, player)
    if (this.leaveFns.length > 0) {
      await this.restorePlayerData(player)
      await this.runGreen('onPlayerLeave', this.leaveFns, player)
    }
    this.ports.flushPlayerData(player)
    this.ports.dropPlayer(player)
    this.playerRecords.delete(player)
  }

  /** game.onEnterArea — runs in the game once the player's entry is verified. */
  onEnterArea(zone: string, fn: PresenceFn): void {
    const key = zoneKey(zone)
    this.zoneEnterFns.set(key, [...(this.zoneEnterFns.get(key) ?? []), fn])
  }

  /** game.onExitArea — runs in the game when a verified member leaves the zone. */
  onExitArea(zone: string, fn: PresenceFn): void {
    const key = zoneKey(zone)
    this.zoneExitFns.set(key, [...(this.zoneExitFns.get(key) ?? []), fn])
  }

  /** Every zone key a script registered for — what the client side must watch. */
  zoneNames(): string[] {
    return [...new Set([...this.zoneEnterFns.keys(), ...this.zoneExitFns.keys()])]
  }

  /**
   * Server: a screen claims its player crossed a named zone. Never trusted —
   * an enter is re-verified against the server's own position view (slack,
   * because positions are ≤10 Hz feet), with grace for an avatar comms has not
   * delivered yet; an exit is always honored (the sweep would drop them
   * anyway). Pre-boot claims queue like asks.
   */
  zoneClaim(zone: string, kind: ZoneClaimKind, player: Player): Promise<ZoneClaimReply> {
    if (!this.hasBooted) {
      return new Promise<ZoneClaimReply>((resolve, reject) => {
        this.preBootZoneClaims.push({ zone, kind, player, resolve, reject })
      })
    }
    // Claims are asks like any other: a client alternating enter/exit at
    // transport rate would otherwise run green code — and a full position
    // scan — as fast as it can send. The cap matches the sweep's own rate.
    // The name arrives off the wire, so check it against the zones this scene
    // actually listens to BEFORE anything is allocated for it: otherwise a
    // client invents a fresh name per claim and every one costs a full scan
    // and a permanent bucket.
    const key = zoneKey(zone)
    if (!this.zoneEnterFns.has(key) && !this.zoneExitFns.has(key)) {
      return Promise.resolve({ ok: false, verified: false })
    }
    if (!this.zoneLimiter.allow(`zone:${key}`, player, this.ports.now())) {
      return Promise.resolve({ ok: false, verified: false })
    }
    try {
      return Promise.resolve(this.settleZoneClaim(zone, kind, player))
    } catch (e) {
      return Promise.reject(e instanceof Error ? e : new Error(String(e)))
    }
  }

  private settleZoneClaim(zone: string, kind: ZoneClaimKind, player: Player): ZoneClaimReply {
    const key = zoneKey(zone)
    if (key === '') throw new Error('a zone claim needs a zone name')
    if (kind === 'exit') {
      this.dropZoneMember(key, player)
      return { ok: true, verified: true }
    }
    const volumes = this.ports.findZones(key)
    if (volumes.length === 0) throw new Error(`no zone named "${zone.trim()}"`)
    const position = this.ports.playerPosition(player)
    if (position === null) {
      // Late-joiner grace: rejecting every arriving player's first entry would
      // be worse than admitting one unverified — the sweep drops them the
      // moment their position arrives outside.
      this.admitZoneMember(key, player)
      return { ok: true, verified: false }
    }
    if (!volumes.some((v) => insideZone(v, position, ZONE_SLACK_M))) {
      this.dropZoneMember(key, player)
      throw new Error(`outside "${zone.trim()}"`)
    }
    this.admitZoneMember(key, player)
    return { ok: true, verified: true }
  }

  private admitZoneMember(key: string, player: Player): void {
    const members = this.zoneMembers.get(key) ?? new Map<Player, number>()
    this.zoneMembers.set(key, members)
    // The lost-sight clock starts at admission and never restarts: re-claiming
    // must not buy a player another grace window the server can't verify.
    if (members.has(player)) return
    members.set(player, 0)
    const fns = this.zoneEnterFns.get(key)
    if (!fns || fns.length === 0) return
    // A zone enter may be this player's first green handler.
    void this.restorePlayerData(player).then(() => this.runGreen('onEnterArea', fns, player))
  }

  private dropZoneMember(key: string, player: Player): void {
    const members = this.zoneMembers.get(key)
    if (!members?.has(player)) return
    members.delete(player)
    if (members.size === 0) this.zoneMembers.delete(key)
    const fns = this.zoneExitFns.get(key)
    if (!fns || fns.length === 0) return
    void this.restorePlayerData(player).then(() => this.runGreen('onExitArea', fns, player))
  }

  /** Server, ~4 Hz: re-check every verified member against the position view. */
  sweepZones(nowMs: number): void {
    if (!this.isServer() || !this.hasBooted) return
    for (const [key, members] of [...this.zoneMembers]) {
      const volumes = this.ports.findZones(key)
      for (const [player, lostSinceMs] of [...members]) {
        if (volumes.length === 0) {
          this.dropZoneMember(key, player)
          continue
        }
        const position = this.ports.playerPosition(player)
        if (position === null) {
          if (lostSinceMs === 0) members.set(player, nowMs)
          else if (nowMs - lostSinceMs > ZONE_LOST_GRACE_MS) this.dropZoneMember(key, player)
          continue
        }
        if (volumes.some((v) => insideZone(v, position, ZONE_SLACK_M))) members.set(player, 0)
        else this.dropZoneMember(key, player)
      }
    }
  }

  /** game.positionOf — feet, ~10×/second; green only. */
  positionOf(player: Player): Vec3 | null {
    this.greenGuard(POSITION_GUARD)
    return this.ports.playerPosition(player)
  }

  /** game.every's green tick — errors card, never wedge the interval. */
  runEvery(fn: () => void | Promise<void>): Promise<void> {
    return this.runGreen('every', [fn])
  }

  /** game.round — read anywhere; number is 0 until the first round lands. */
  get round(): RoundInfo {
    return asRoundInfo(this.state[ROUND_STATE_KEY])
  }

  /** game.onRoundStart — green (§12 #1): screens react through onStateChange. */
  onRoundStart(fn: (round: RoundInfo) => void | Promise<void>): void {
    this.roundStartFns.push(fn)
  }

  /** game.newRound — green only: bumps the monotonic number, publishes the
   * seed drawn for this round, and runs the onRoundStart hooks. */
  newRound(): RoundInfo {
    this.greenGuard(NEW_ROUND_GUARD)
    const tuple = this.beginRound(this.round.number + 1)
    // deferred a microtask: the caller's own green span finishes first
    void Promise.resolve().then(() => this.runGreen('onRoundStart', this.roundStartFns, tuple))
    return tuple
  }

  // The tuple rides the facts path like any state key — written directly so
  // boot can start round 1 through the same door a green handler uses.
  private beginRound(number: number): RoundInfo {
    const tuple: RoundInfo = {
      number,
      seed: this.ports.takeNextSeed(),
      phase: 0,
      phaseStartMs: this.ports.now(),
      configVersion: configVersionNow()
    }
    this.state[ROUND_STATE_KEY] = tuple
    this.dirty.set(ROUND_STATE_KEY, tuple)
    return tuple
  }

  /** Client dispatch of an incoming tell. Unmatched tells are dropped quietly —
   * a screen may legitimately not care — but malformed ones surface. */
  handleTell(name: string, json: string): void {
    const entry = this.handlers.get(name)
    trace('you', '← game', name, json, entry ? undefined : 'no handler on this screen')
    if (!entry) return
    let data: unknown
    try {
      data = json === '' ? undefined : JSON.parse(json)
    } catch {
      this.ports.emitError({ side: 'you', name, message: `'${name}' arrived with invalid JSON.` })
      return
    }
    try {
      void entry.fn(data, '')
    } catch (e) {
      this.ports.emitError({ side: 'you', name, message: e instanceof Error ? e.message : String(e) })
    }
  }
}
